.PHONY: test build ui-build lint e2e-dry-run

test:
	cd contracts/go && rtk go test ./...
	cd agent && rtk go test ./...
	cd cli && rtk go test ./...
	cd cloud && rtk go test ./...

build:
	rtk mkdir -p bin
	cd agent && rtk go build -o ../bin/opsi-agent ./cmd/opsi-agent
	cd cli && rtk go build -o ../bin/opsi ./cmd/opsi
	cd cloud && rtk go build -o ../bin/opsi-cloud ./cmd/opsi-cloud

ui-build:
	cd cli/ui && rtk npm run build

lint:
	cd agent && rtk go vet ./...
	cd cli && rtk go vet ./...
	cd cloud && rtk go vet ./...
	cd contracts/go && rtk go vet ./...

e2e-dry-run:
	cd agent && rtk go test ./internal/cloudrunner
