package postgres

import (
	"context"
	"database/sql"
)

func Migrate(ctx context.Context, db *sql.DB) error {
	statements := []string{
		`CREATE TABLE IF NOT EXISTS users (
			id TEXT PRIMARY KEY,
			email TEXT UNIQUE NOT NULL,
			created_at TIMESTAMPTZ NOT NULL DEFAULT now()
		)`,
		`CREATE TABLE IF NOT EXISTS organizations (
			id TEXT PRIMARY KEY,
			name TEXT NOT NULL,
			slug TEXT UNIQUE NOT NULL,
			plan TEXT NOT NULL DEFAULT 'free',
			default_region TEXT,
			status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','suspended','deleted')),
			created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
		)`,
		`CREATE TABLE IF NOT EXISTS user_memberships (
			id TEXT PRIMARY KEY,
			org_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
			user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			role TEXT NOT NULL CHECK (role IN ('owner','admin','developer','viewer','support')),
			status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','invited','disabled')),
			created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			UNIQUE (org_id, user_id)
		)`,
		`CREATE TABLE IF NOT EXISTS projects (
			id TEXT PRIMARY KEY,
			org_id TEXT REFERENCES organizations(id),
			name TEXT NOT NULL,
			slug TEXT,
			status TEXT NOT NULL DEFAULT 'no_nodes',
			created_by TEXT REFERENCES users(id),
			created_at TIMESTAMPTZ NOT NULL DEFAULT now()
		)`,
		`ALTER TABLE projects ADD COLUMN IF NOT EXISTS org_id TEXT REFERENCES organizations(id)`,
		`ALTER TABLE projects ADD COLUMN IF NOT EXISTS slug TEXT`,
		`ALTER TABLE projects ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'no_nodes'`,
		`ALTER TABLE projects ADD COLUMN IF NOT EXISTS created_by TEXT REFERENCES users(id)`,
		`ALTER TABLE projects ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now()`,
		`CREATE UNIQUE INDEX IF NOT EXISTS projects_org_slug_idx ON projects(org_id, slug) WHERE org_id IS NOT NULL AND slug IS NOT NULL`,
		`CREATE TABLE IF NOT EXISTS project_memberships (
			project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
			user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			role TEXT NOT NULL CHECK (role IN ('owner','admin','developer','viewer','support','Owner','Developer','Viewer')),
			created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			PRIMARY KEY (project_id, user_id)
		)`,
		`ALTER TABLE project_memberships DROP CONSTRAINT IF EXISTS project_memberships_role_check`,
		`ALTER TABLE project_memberships ADD CONSTRAINT project_memberships_role_check CHECK (role IN ('owner','admin','developer','viewer','support','Owner','Developer','Viewer'))`,
		`CREATE TABLE IF NOT EXISTS environments (
			id TEXT PRIMARY KEY,
			org_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
			project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
			name TEXT NOT NULL,
			type TEXT NOT NULL CHECK (type IN ('dev','staging','prod','custom')),
			status TEXT NOT NULL DEFAULT 'active',
			created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			UNIQUE (project_id, name)
		)`,
		`CREATE TABLE IF NOT EXISTS runtimes (
			id TEXT PRIMARY KEY,
			org_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
			project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
			environment_id TEXT NOT NULL REFERENCES environments(id) ON DELETE CASCADE,
			name TEXT NOT NULL,
			type TEXT NOT NULL DEFAULT 'k3s',
			status TEXT NOT NULL DEFAULT 'no_nodes',
			server_node_id TEXT,
			k3s_cluster_id TEXT,
			network_cidr TEXT,
			service_cidr TEXT,
			created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			UNIQUE (project_id, environment_id, name)
		)`,
		`CREATE TABLE IF NOT EXISTS nodes (
			id TEXT PRIMARY KEY,
			org_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
			project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
			environment_id TEXT NOT NULL REFERENCES environments(id) ON DELETE CASCADE,
			runtime_id TEXT NOT NULL REFERENCES runtimes(id) ON DELETE CASCADE,
			name TEXT NOT NULL,
			role TEXT NOT NULL CHECK (role IN ('server','worker')),
			status TEXT NOT NULL,
			public_host TEXT,
			private_ip TEXT,
			provider TEXT,
			region TEXT,
			os_name TEXT,
			os_version TEXT,
			arch TEXT,
			cpu_cores INTEGER,
			memory_mb INTEGER,
			disk_total_gb INTEGER,
			k3s_role TEXT DEFAULT 'unknown',
			k3s_status TEXT,
			k3s_version TEXT,
			agent_id TEXT,
			agent_version TEXT,
			last_seen_at TIMESTAMPTZ,
			last_inventory_at TIMESTAMPTZ,
			failure_code TEXT,
			failure_message_redacted TEXT,
			created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			UNIQUE (runtime_id, name)
		)`,
		`ALTER TABLE nodes ADD COLUMN IF NOT EXISTS k3s_status TEXT`,
		`CREATE INDEX IF NOT EXISTS nodes_project_status_idx ON nodes(project_id, status)`,
		`CREATE TABLE IF NOT EXISTS agents (
			id TEXT PRIMARY KEY,
			org_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
			project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
			runtime_id TEXT NOT NULL REFERENCES runtimes(id) ON DELETE CASCADE,
			node_id TEXT NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
			public_key_fingerprint TEXT NOT NULL,
			credential_hash TEXT,
			version TEXT,
			capabilities JSONB NOT NULL DEFAULT '{}'::jsonb,
			status TEXT NOT NULL DEFAULT 'registering',
			last_seen_at TIMESTAMPTZ,
			last_rotation_at TIMESTAMPTZ,
			created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
		)`,
		`ALTER TABLE agents ADD COLUMN IF NOT EXISTS credential_hash TEXT`,
		`CREATE INDEX IF NOT EXISTS agents_project_status_idx ON agents(project_id, status)`,
		`CREATE TABLE IF NOT EXISTS bootstrap_sessions (
			id TEXT PRIMARY KEY,
			org_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
			project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
			environment_id TEXT NOT NULL REFERENCES environments(id) ON DELETE CASCADE,
			runtime_id TEXT NOT NULL REFERENCES runtimes(id) ON DELETE CASCADE,
			node_id TEXT REFERENCES nodes(id) ON DELETE SET NULL,
			created_by TEXT REFERENCES users(id),
			role TEXT NOT NULL,
			status TEXT NOT NULL,
			idempotency_key TEXT NOT NULL,
			public_host TEXT,
			ssh_port INTEGER,
			ssh_username TEXT,
			auth_method TEXT,
			credential_ref TEXT,
			credential_expires_at TIMESTAMPTZ,
			started_at TIMESTAMPTZ,
			finished_at TIMESTAMPTZ,
			expires_at TIMESTAMPTZ NOT NULL,
			failure_code TEXT,
			failure_message_redacted TEXT,
			created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			UNIQUE (project_id, idempotency_key)
		)`,
		`CREATE INDEX IF NOT EXISTS bootstrap_sessions_project_status_idx ON bootstrap_sessions(project_id, status, created_at)`,
		`CREATE TABLE IF NOT EXISTS bootstrap_events (
			id TEXT PRIMARY KEY,
			org_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
			project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
			session_id TEXT NOT NULL REFERENCES bootstrap_sessions(id) ON DELETE CASCADE,
			node_id TEXT REFERENCES nodes(id) ON DELETE SET NULL,
			level TEXT NOT NULL,
			step TEXT NOT NULL,
			message_redacted TEXT NOT NULL,
			progress_percent INTEGER NOT NULL DEFAULT 0,
			created_at TIMESTAMPTZ NOT NULL DEFAULT now()
		)`,
		`CREATE INDEX IF NOT EXISTS bootstrap_events_session_created_idx ON bootstrap_events(session_id, created_at)`,
		`CREATE TABLE IF NOT EXISTS bootstrap_credentials (
			session_id TEXT PRIMARY KEY REFERENCES bootstrap_sessions(id) ON DELETE CASCADE,
			ciphertext BYTEA NOT NULL,
			nonce BYTEA NOT NULL,
			expires_at TIMESTAMPTZ NOT NULL,
			consumed_at TIMESTAMPTZ
		)`,
		`CREATE INDEX IF NOT EXISTS bootstrap_credentials_expires_idx ON bootstrap_credentials(expires_at)`,
		`CREATE TABLE IF NOT EXISTS bootstrap_registration_tokens (
			session_id TEXT PRIMARY KEY REFERENCES bootstrap_sessions(id) ON DELETE CASCADE,
			org_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
			project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
			node_id TEXT NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
			token_hash TEXT NOT NULL UNIQUE,
			token_ciphertext BYTEA NOT NULL,
			token_nonce BYTEA NOT NULL,
			expires_at TIMESTAMPTZ NOT NULL,
			worker_consumed_at TIMESTAMPTZ,
			exchanged_at TIMESTAMPTZ
		)`,
		`CREATE INDEX IF NOT EXISTS bootstrap_registration_tokens_project_idx ON bootstrap_registration_tokens(project_id, expires_at)`,
		`CREATE TABLE IF NOT EXISTS rate_limits (
			key TEXT PRIMARY KEY,
			count INTEGER NOT NULL,
			resets_at TIMESTAMPTZ NOT NULL,
			updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
		)`,
		`CREATE TABLE IF NOT EXISTS control_services (
			id TEXT PRIMARY KEY,
			org_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
			project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
			environment_id TEXT NOT NULL REFERENCES environments(id) ON DELETE CASCADE,
			runtime_id TEXT NOT NULL REFERENCES runtimes(id) ON DELETE CASCADE,
			name TEXT NOT NULL,
			type TEXT NOT NULL,
			status TEXT NOT NULL,
			source_type TEXT NOT NULL,
			repo_url TEXT,
			image TEXT,
			namespace TEXT NOT NULL,
			ports JSONB NOT NULL DEFAULT '[]'::jsonb,
			health_check JSONB NOT NULL DEFAULT '{}'::jsonb,
			resources JSONB NOT NULL DEFAULT '{}'::jsonb,
			replicas_desired INTEGER NOT NULL DEFAULT 1,
			created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			UNIQUE (project_id, name)
		)`,
		`CREATE INDEX IF NOT EXISTS control_services_project_status_idx ON control_services(project_id, status)`,
		`CREATE TABLE IF NOT EXISTS deployment_jobs (
			id TEXT PRIMARY KEY,
			org_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
			project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
			environment_id TEXT NOT NULL REFERENCES environments(id) ON DELETE CASCADE,
			runtime_id TEXT NOT NULL REFERENCES runtimes(id) ON DELETE CASCADE,
			service_id TEXT NOT NULL REFERENCES control_services(id) ON DELETE CASCADE,
			status TEXT NOT NULL,
			deployment_plan_hash TEXT,
			idempotency_key TEXT NOT NULL,
			requested_by TEXT REFERENCES users(id),
			agent_id TEXT REFERENCES agents(id),
			node_id TEXT REFERENCES nodes(id),
			started_at TIMESTAMPTZ,
			finished_at TIMESTAMPTZ,
			failure_code TEXT,
			failure_message_redacted TEXT,
			created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			UNIQUE (project_id, service_id, idempotency_key)
		)`,
		`CREATE INDEX IF NOT EXISTS deployment_jobs_project_status_idx ON deployment_jobs(project_id, status, created_at)`,
		`CREATE TABLE IF NOT EXISTS deployment_events (
			id TEXT PRIMARY KEY,
			org_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
			project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
			deployment_id TEXT NOT NULL REFERENCES deployment_jobs(id) ON DELETE CASCADE,
			service_id TEXT NOT NULL REFERENCES control_services(id) ON DELETE CASCADE,
			level TEXT NOT NULL,
			step TEXT NOT NULL,
			message_redacted TEXT NOT NULL,
			progress_percent INTEGER NOT NULL DEFAULT 0,
			request_id TEXT,
			created_at TIMESTAMPTZ NOT NULL DEFAULT now()
		)`,
		`CREATE INDEX IF NOT EXISTS deployment_events_deployment_created_idx ON deployment_events(deployment_id, created_at)`,
		`CREATE TABLE IF NOT EXISTS cloud_audit_events (
			id TEXT PRIMARY KEY,
			org_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
			project_id TEXT REFERENCES projects(id) ON DELETE SET NULL,
			actor_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
			actor_type TEXT NOT NULL,
			action TEXT NOT NULL,
			resource_type TEXT NOT NULL,
			resource_id TEXT NOT NULL,
			result TEXT NOT NULL,
			ip_address TEXT,
			user_agent TEXT,
			metadata_redacted JSONB NOT NULL DEFAULT '{}'::jsonb,
			created_at TIMESTAMPTZ NOT NULL DEFAULT now()
		)`,
		`CREATE INDEX IF NOT EXISTS cloud_audit_events_org_created_idx ON cloud_audit_events(org_id, created_at)`,
		`CREATE OR REPLACE FUNCTION prevent_cloud_audit_mutation() RETURNS trigger AS $$
		BEGIN
			RAISE EXCEPTION 'cloud_audit_events is append-only';
		END;
		$$ LANGUAGE plpgsql`,
		`DROP TRIGGER IF EXISTS cloud_audit_events_no_update ON cloud_audit_events`,
		`DROP TRIGGER IF EXISTS cloud_audit_events_no_delete ON cloud_audit_events`,
		`CREATE TRIGGER cloud_audit_events_no_update BEFORE UPDATE ON cloud_audit_events FOR EACH ROW EXECUTE FUNCTION prevent_cloud_audit_mutation()`,
		`CREATE TRIGGER cloud_audit_events_no_delete BEFORE DELETE ON cloud_audit_events FOR EACH ROW EXECUTE FUNCTION prevent_cloud_audit_mutation()`,
		`CREATE TABLE IF NOT EXISTS idempotency_keys (
			scope TEXT NOT NULL,
			key TEXT NOT NULL,
			resource_type TEXT NOT NULL,
			resource_id TEXT NOT NULL,
			created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			PRIMARY KEY (scope, key)
		)`,
		`CREATE TABLE IF NOT EXISTS personal_access_tokens (
			id TEXT PRIMARY KEY,
			user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			token_hash TEXT NOT NULL,
			expires_at TIMESTAMPTZ NOT NULL,
			revoked BOOLEAN NOT NULL DEFAULT false,
			created_at TIMESTAMPTZ NOT NULL DEFAULT now()
		)`,
		`CREATE INDEX IF NOT EXISTS personal_access_tokens_user_id_idx ON personal_access_tokens(user_id)`,
		`CREATE TABLE IF NOT EXISTS otp_requests (
			id TEXT PRIMARY KEY,
			project_id TEXT NOT NULL,
			user_id TEXT NOT NULL,
			purpose TEXT NOT NULL,
			salt TEXT NOT NULL,
			code_hash TEXT NOT NULL,
			expires_at TIMESTAMPTZ NOT NULL,
			used_at TIMESTAMPTZ,
			created_at TIMESTAMPTZ NOT NULL DEFAULT now()
		)`,
		`CREATE INDEX IF NOT EXISTS otp_requests_user_created_idx ON otp_requests(user_id, created_at)`,
	}
	for _, statement := range statements {
		if _, err := db.ExecContext(ctx, statement); err != nil {
			return err
		}
	}
	return nil
}
