package postgres

import (
	"context"
	"database/sql"
)

func Migrate(ctx context.Context, db *sql.DB) error {
	statements := []string{
		`CREATE TABLE IF NOT EXISTS users (
			id TEXT PRIMARY KEY,
			email TEXT UNIQUE NOT NULL,
			created_at TIMESTAMPTZ NOT NULL DEFAULT now()
		)`,
		`ALTER TABLE users ADD COLUMN IF NOT EXISTS display_name TEXT`,
		`CREATE TABLE IF NOT EXISTS organizations (
			id TEXT PRIMARY KEY,
			name TEXT NOT NULL,
			slug TEXT UNIQUE NOT NULL,
			plan TEXT NOT NULL DEFAULT 'free',
			default_region TEXT,
			status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','suspended','deleted')),
			created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
		)`,
		`CREATE TABLE IF NOT EXISTS user_memberships (
			id TEXT PRIMARY KEY,
			org_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
			user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			role TEXT NOT NULL CHECK (role IN ('owner','admin','developer','viewer','support')),
			status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','invited','disabled')),
			created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			UNIQUE (org_id, user_id)
		)`,
		`CREATE TABLE IF NOT EXISTS projects (
			id TEXT PRIMARY KEY,
			org_id TEXT REFERENCES organizations(id),
			name TEXT NOT NULL,
			slug TEXT,
			status TEXT NOT NULL DEFAULT 'no_nodes',
			created_by TEXT REFERENCES users(id),
			created_at TIMESTAMPTZ NOT NULL DEFAULT now()
		)`,
		`ALTER TABLE projects ADD COLUMN IF NOT EXISTS org_id TEXT REFERENCES organizations(id)`,
		`ALTER TABLE projects ADD COLUMN IF NOT EXISTS slug TEXT`,
		`ALTER TABLE projects ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'no_nodes'`,
		`ALTER TABLE projects ADD COLUMN IF NOT EXISTS created_by TEXT REFERENCES users(id)`,
		`ALTER TABLE projects ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now()`,
		`CREATE UNIQUE INDEX IF NOT EXISTS projects_org_slug_idx ON projects(org_id, slug) WHERE org_id IS NOT NULL AND slug IS NOT NULL`,
		`CREATE TABLE IF NOT EXISTS project_memberships (
			project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
			user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			role TEXT NOT NULL CHECK (role IN ('owner','admin','developer','viewer','support','Owner','Developer','Viewer')),
			created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			PRIMARY KEY (project_id, user_id)
		)`,
		`ALTER TABLE project_memberships DROP CONSTRAINT IF EXISTS project_memberships_role_check`,
		`ALTER TABLE project_memberships ADD CONSTRAINT project_memberships_role_check CHECK (role IN ('owner','admin','developer','viewer','support','Owner','Developer','Viewer'))`,
		`CREATE TABLE IF NOT EXISTS environments (
			id TEXT PRIMARY KEY,
			org_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
			project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
			name TEXT NOT NULL,
			type TEXT NOT NULL CHECK (type IN ('dev','staging','prod','custom')),
			status TEXT NOT NULL DEFAULT 'active',
			created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			UNIQUE (project_id, name)
		)`,
		`CREATE TABLE IF NOT EXISTS runtimes (
			id TEXT PRIMARY KEY,
			org_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
			project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
			environment_id TEXT NOT NULL REFERENCES environments(id) ON DELETE CASCADE,
			name TEXT NOT NULL,
			type TEXT NOT NULL DEFAULT 'k3s',
			status TEXT NOT NULL DEFAULT 'no_nodes',
			server_node_id TEXT,
			k3s_cluster_id TEXT,
			network_cidr TEXT,
			service_cidr TEXT,
			created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			UNIQUE (project_id, environment_id, name)
		)`,
		`CREATE TABLE IF NOT EXISTS nodes (
			id TEXT PRIMARY KEY,
			org_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
			project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
			environment_id TEXT NOT NULL REFERENCES environments(id) ON DELETE CASCADE,
			runtime_id TEXT NOT NULL REFERENCES runtimes(id) ON DELETE CASCADE,
			name TEXT NOT NULL,
			role TEXT NOT NULL CHECK (role IN ('server','worker')),
			status TEXT NOT NULL,
			public_host TEXT,
			private_ip TEXT,
			provider TEXT,
			region TEXT,
			os_name TEXT,
			os_version TEXT,
			arch TEXT,
			cpu_cores INTEGER,
			memory_mb INTEGER,
			disk_total_gb INTEGER,
			k3s_role TEXT DEFAULT 'unknown',
			k3s_status TEXT,
			k3s_version TEXT,
			agent_id TEXT,
			agent_version TEXT,
			last_seen_at TIMESTAMPTZ,
			last_inventory_at TIMESTAMPTZ,
			failure_code TEXT,
			failure_message_redacted TEXT,
			created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			UNIQUE (runtime_id, name)
		)`,
		`ALTER TABLE nodes ADD COLUMN IF NOT EXISTS k3s_status TEXT`,
		`ALTER TABLE nodes ADD COLUMN IF NOT EXISTS agent_endpoint TEXT`,
		`ALTER TABLE nodes ADD COLUMN IF NOT EXISTS agent_port INTEGER`,
		`ALTER TABLE nodes ADD COLUMN IF NOT EXISTS agent_tls_server_name TEXT`,
		`ALTER TABLE nodes ADD COLUMN IF NOT EXISTS agent_cert_sha256 TEXT`,
		`CREATE INDEX IF NOT EXISTS nodes_project_status_idx ON nodes(project_id, status)`,
		`CREATE TABLE IF NOT EXISTS agents (
			id TEXT PRIMARY KEY,
			org_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
			project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
			runtime_id TEXT NOT NULL REFERENCES runtimes(id) ON DELETE CASCADE,
			node_id TEXT NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
			public_key_fingerprint TEXT NOT NULL,
			credential_hash TEXT,
			version TEXT,
			capabilities JSONB NOT NULL DEFAULT '{}'::jsonb,
			status TEXT NOT NULL DEFAULT 'registering',
			last_seen_at TIMESTAMPTZ,
			last_rotation_at TIMESTAMPTZ,
			created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
		)`,
		`ALTER TABLE agents ADD COLUMN IF NOT EXISTS credential_hash TEXT`,
		`CREATE INDEX IF NOT EXISTS agents_project_status_idx ON agents(project_id, status)`,
		`CREATE TABLE IF NOT EXISTS bootstrap_sessions (
			id TEXT PRIMARY KEY,
			org_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
			project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
			environment_id TEXT NOT NULL REFERENCES environments(id) ON DELETE CASCADE,
			runtime_id TEXT NOT NULL REFERENCES runtimes(id) ON DELETE CASCADE,
			node_id TEXT REFERENCES nodes(id) ON DELETE SET NULL,
			created_by TEXT REFERENCES users(id),
			role TEXT NOT NULL,
			status TEXT NOT NULL,
			idempotency_key TEXT NOT NULL,
			public_host TEXT,
			ssh_port INTEGER,
			ssh_username TEXT,
			auth_method TEXT,
			credential_ref TEXT,
			credential_expires_at TIMESTAMPTZ,
			started_at TIMESTAMPTZ,
			finished_at TIMESTAMPTZ,
			expires_at TIMESTAMPTZ NOT NULL,
			failure_code TEXT,
			failure_message_redacted TEXT,
			created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			UNIQUE (project_id, idempotency_key)
		)`,
		`CREATE INDEX IF NOT EXISTS bootstrap_sessions_project_status_idx ON bootstrap_sessions(project_id, status, created_at)`,
		`ALTER TABLE bootstrap_sessions ADD COLUMN IF NOT EXISTS lease_owner TEXT`,
		`ALTER TABLE bootstrap_sessions ADD COLUMN IF NOT EXISTS lease_token_hash TEXT`,
		`ALTER TABLE bootstrap_sessions ADD COLUMN IF NOT EXISTS lease_expires_at TIMESTAMPTZ`,
		`ALTER TABLE bootstrap_sessions ADD COLUMN IF NOT EXISTS leased_at TIMESTAMPTZ`,
		`ALTER TABLE bootstrap_sessions ADD COLUMN IF NOT EXISTS attempt_count INTEGER NOT NULL DEFAULT 0`,
		`ALTER TABLE bootstrap_sessions ADD COLUMN IF NOT EXISTS max_attempts INTEGER NOT NULL DEFAULT 3`,
		`ALTER TABLE bootstrap_sessions ADD COLUMN IF NOT EXISTS next_attempt_at TIMESTAMPTZ`,
		`ALTER TABLE bootstrap_sessions ADD COLUMN IF NOT EXISTS lease_heartbeat_at TIMESTAMPTZ`,
		`ALTER TABLE bootstrap_sessions ADD COLUMN IF NOT EXISTS last_failure_code TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE bootstrap_sessions ADD COLUMN IF NOT EXISTS last_failure_message_redacted TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE bootstrap_sessions ADD COLUMN IF NOT EXISTS dead_lettered_at TIMESTAMPTZ`,
		`CREATE INDEX IF NOT EXISTS bootstrap_sessions_retry_queue_idx ON bootstrap_sessions(status, next_attempt_at, created_at, id) WHERE status IN ('created','pending','retry_wait')`,
		`CREATE INDEX IF NOT EXISTS bootstrap_sessions_lease_expiry_idx ON bootstrap_sessions(status, lease_expires_at) WHERE lease_expires_at IS NOT NULL`,
		`CREATE TABLE IF NOT EXISTS bootstrap_events (
			id TEXT PRIMARY KEY,
			org_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
			project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
			session_id TEXT NOT NULL REFERENCES bootstrap_sessions(id) ON DELETE CASCADE,
			node_id TEXT REFERENCES nodes(id) ON DELETE SET NULL,
			level TEXT NOT NULL,
			step TEXT NOT NULL,
			message_redacted TEXT NOT NULL,
			progress_percent INTEGER NOT NULL DEFAULT 0,
			created_at TIMESTAMPTZ NOT NULL DEFAULT now()
		)`,
		`CREATE INDEX IF NOT EXISTS bootstrap_events_session_created_idx ON bootstrap_events(session_id, created_at)`,
		`CREATE TABLE IF NOT EXISTS bootstrap_credentials (
			session_id TEXT PRIMARY KEY REFERENCES bootstrap_sessions(id) ON DELETE CASCADE,
			ciphertext BYTEA NOT NULL,
			nonce BYTEA NOT NULL,
			expires_at TIMESTAMPTZ NOT NULL,
			consumed_at TIMESTAMPTZ
		)`,
		`CREATE INDEX IF NOT EXISTS bootstrap_credentials_expires_idx ON bootstrap_credentials(expires_at)`,
		`CREATE TABLE IF NOT EXISTS bootstrap_registration_tokens (
			session_id TEXT PRIMARY KEY REFERENCES bootstrap_sessions(id) ON DELETE CASCADE,
			org_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
			project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
			node_id TEXT NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
			token_hash TEXT NOT NULL UNIQUE,
			token_ciphertext BYTEA NOT NULL,
			token_nonce BYTEA NOT NULL,
			expires_at TIMESTAMPTZ NOT NULL,
			worker_consumed_at TIMESTAMPTZ,
			exchanged_at TIMESTAMPTZ
		)`,
		`CREATE INDEX IF NOT EXISTS bootstrap_registration_tokens_project_idx ON bootstrap_registration_tokens(project_id, expires_at)`,
		`CREATE TABLE IF NOT EXISTS rate_limits (
			key TEXT PRIMARY KEY,
			count INTEGER NOT NULL,
			resets_at TIMESTAMPTZ NOT NULL,
			updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
		)`,
		`CREATE TABLE IF NOT EXISTS control_services (
			id TEXT PRIMARY KEY,
			org_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
			project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
			environment_id TEXT NOT NULL REFERENCES environments(id) ON DELETE CASCADE,
			runtime_id TEXT NOT NULL REFERENCES runtimes(id) ON DELETE CASCADE,
			name TEXT NOT NULL,
			type TEXT NOT NULL,
			status TEXT NOT NULL,
			source_type TEXT NOT NULL,
			repo_url TEXT,
			image TEXT,
			branch TEXT,
			git_sha TEXT,
			build_method TEXT,
			build_context TEXT,
			dockerfile TEXT,
			manifest_path TEXT,
			watch_paths JSONB NOT NULL DEFAULT '[]'::jsonb,
			container_port INTEGER,
			health_path TEXT,
			replicas_desired INTEGER NOT NULL DEFAULT 1,
			namespace TEXT NOT NULL,
			ports JSONB NOT NULL DEFAULT '[]'::jsonb,
			health_check JSONB NOT NULL DEFAULT '{}'::jsonb,
			resources JSONB NOT NULL DEFAULT '{}'::jsonb,
			bindings JSONB NOT NULL DEFAULT '[]'::jsonb,
			created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			UNIQUE (project_id, name)
		)`,
		`ALTER TABLE control_services ADD COLUMN IF NOT EXISTS branch TEXT`,
		`ALTER TABLE control_services ADD COLUMN IF NOT EXISTS git_sha TEXT`,
		`ALTER TABLE control_services ADD COLUMN IF NOT EXISTS build_method TEXT`,
		`ALTER TABLE control_services ADD COLUMN IF NOT EXISTS build_context TEXT`,
		`ALTER TABLE control_services ADD COLUMN IF NOT EXISTS dockerfile TEXT`,
		`ALTER TABLE control_services ADD COLUMN IF NOT EXISTS manifest_path TEXT`,
		`ALTER TABLE control_services ADD COLUMN IF NOT EXISTS watch_paths JSONB NOT NULL DEFAULT '[]'::jsonb`,
		`ALTER TABLE control_services ADD COLUMN IF NOT EXISTS container_port INTEGER`,
		`ALTER TABLE control_services ADD COLUMN IF NOT EXISTS health_path TEXT`,
		`ALTER TABLE control_services ADD COLUMN IF NOT EXISTS replicas_desired INTEGER NOT NULL DEFAULT 1`,
		`ALTER TABLE control_services ADD COLUMN IF NOT EXISTS resources JSONB NOT NULL DEFAULT '{}'::jsonb`,
		`ALTER TABLE control_services ADD COLUMN IF NOT EXISTS bindings JSONB NOT NULL DEFAULT '[]'::jsonb`,
		`CREATE INDEX IF NOT EXISTS control_services_project_status_idx ON control_services(project_id, status)`,
		`CREATE TABLE IF NOT EXISTS deployment_jobs (
			id TEXT PRIMARY KEY,
			org_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
			project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
			environment_id TEXT NOT NULL REFERENCES environments(id) ON DELETE CASCADE,
			runtime_id TEXT NOT NULL REFERENCES runtimes(id) ON DELETE CASCADE,
			service_id TEXT NOT NULL REFERENCES control_services(id) ON DELETE CASCADE,
			status TEXT NOT NULL,
			action TEXT NOT NULL DEFAULT 'deploy',
			deployment_plan_hash TEXT,
			manifest_hash TEXT,
			intent_hash TEXT,
			deployment_intent_json JSONB NOT NULL DEFAULT '{}'::jsonb,
			previous_revision_ref TEXT,
			rollback_eligible BOOLEAN NOT NULL DEFAULT false,
			rollback_blocked_reason TEXT,
			idempotency_key TEXT NOT NULL,
			requested_by TEXT REFERENCES users(id),
			agent_id TEXT REFERENCES agents(id),
			node_id TEXT REFERENCES nodes(id),
			lease_token TEXT,
			lease_expires_at TIMESTAMPTZ,
			attempt_count INTEGER NOT NULL DEFAULT 0,
			max_attempts INTEGER NOT NULL DEFAULT 3,
			started_at TIMESTAMPTZ,
			finished_at TIMESTAMPTZ,
			failure_code TEXT,
			failure_message_redacted TEXT,
			created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			UNIQUE (project_id, service_id, idempotency_key)
		)`,
		`ALTER TABLE deployment_jobs ADD COLUMN IF NOT EXISTS deployment_plan_hash TEXT`,
		`ALTER TABLE deployment_jobs ADD COLUMN IF NOT EXISTS manifest_hash TEXT`,
		`ALTER TABLE deployment_jobs ADD COLUMN IF NOT EXISTS intent_hash TEXT`,
		`ALTER TABLE deployment_jobs ADD COLUMN IF NOT EXISTS deployment_intent_json JSONB NOT NULL DEFAULT '{}'::jsonb`,
		`ALTER TABLE deployment_jobs ADD COLUMN IF NOT EXISTS previous_revision_ref TEXT`,
		`ALTER TABLE deployment_jobs ADD COLUMN IF NOT EXISTS rollback_eligible BOOLEAN NOT NULL DEFAULT false`,
		`ALTER TABLE deployment_jobs ADD COLUMN IF NOT EXISTS rollback_blocked_reason TEXT`,
		`ALTER TABLE deployment_jobs ADD COLUMN IF NOT EXISTS agent_id TEXT REFERENCES agents(id)`,
		`ALTER TABLE deployment_jobs ADD COLUMN IF NOT EXISTS node_id TEXT REFERENCES nodes(id)`,
		`ALTER TABLE deployment_jobs ADD COLUMN IF NOT EXISTS failure_code TEXT`,
		`ALTER TABLE deployment_jobs ADD COLUMN IF NOT EXISTS failure_message_redacted TEXT`,
		`ALTER TABLE deployment_jobs ADD COLUMN IF NOT EXISTS action TEXT NOT NULL DEFAULT 'deploy'`,
		`ALTER TABLE deployment_jobs ADD COLUMN IF NOT EXISTS lease_token TEXT`,
		`ALTER TABLE deployment_jobs ADD COLUMN IF NOT EXISTS lease_expires_at TIMESTAMPTZ`,
		`ALTER TABLE deployment_jobs ADD COLUMN IF NOT EXISTS attempt_count INTEGER NOT NULL DEFAULT 0`,
		`ALTER TABLE deployment_jobs ADD COLUMN IF NOT EXISTS max_attempts INTEGER NOT NULL DEFAULT 3`,
		`CREATE INDEX IF NOT EXISTS deployment_jobs_project_status_idx ON deployment_jobs(project_id, status, created_at)`,
		`CREATE INDEX IF NOT EXISTS deployment_jobs_lease_expiry_idx ON deployment_jobs(project_id, status, lease_expires_at)`,
		`CREATE TABLE IF NOT EXISTS node_lifecycle_jobs (
			id TEXT PRIMARY KEY,
			org_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
			project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
			runtime_id TEXT NOT NULL REFERENCES runtimes(id) ON DELETE CASCADE,
			action TEXT NOT NULL,
			status TEXT NOT NULL,
			target_node_id TEXT NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
			target_node_name TEXT NOT NULL,
			node_id TEXT NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
			agent_id TEXT REFERENCES agents(id),
			requested_by TEXT REFERENCES users(id),
			idempotency_key TEXT,
			confirm_remove BOOLEAN NOT NULL DEFAULT false,
			lease_token TEXT,
			lease_expires_at TIMESTAMPTZ,
			attempt_count INTEGER NOT NULL DEFAULT 0,
			max_attempts INTEGER NOT NULL DEFAULT 3,
			failure_code TEXT,
			failure_message_redacted TEXT,
			verified BOOLEAN NOT NULL DEFAULT false,
			finished_at TIMESTAMPTZ,
			created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			UNIQUE (project_id, target_node_id, action, idempotency_key)
		)`,
		`CREATE INDEX IF NOT EXISTS node_lifecycle_jobs_project_status_idx ON node_lifecycle_jobs(project_id, status, created_at)`,
		`CREATE INDEX IF NOT EXISTS node_lifecycle_jobs_lease_expiry_idx ON node_lifecycle_jobs(project_id, status, lease_expires_at)`,
		`CREATE TABLE IF NOT EXISTS service_deployment_locks (
			service_id TEXT PRIMARY KEY REFERENCES control_services(id) ON DELETE CASCADE,
			project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
			deployment_id TEXT NOT NULL REFERENCES deployment_jobs(id) ON DELETE CASCADE,
			expires_at TIMESTAMPTZ NOT NULL,
			created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
		)`,
		`CREATE INDEX IF NOT EXISTS service_deployment_locks_project_expiry_idx ON service_deployment_locks(project_id, expires_at)`,
		`CREATE TABLE IF NOT EXISTS deployment_events (
			id TEXT PRIMARY KEY,
			org_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
			project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
			deployment_id TEXT NOT NULL REFERENCES deployment_jobs(id) ON DELETE CASCADE,
			service_id TEXT NOT NULL REFERENCES control_services(id) ON DELETE CASCADE,
			level TEXT NOT NULL,
			step TEXT NOT NULL,
			message_redacted TEXT NOT NULL,
			progress_percent INTEGER NOT NULL DEFAULT 0,
			request_id TEXT,
			created_at TIMESTAMPTZ NOT NULL DEFAULT now()
		)`,
		`CREATE INDEX IF NOT EXISTS deployment_events_deployment_created_idx ON deployment_events(deployment_id, created_at)`,
		`CREATE TABLE IF NOT EXISTS relay_jobs (
			id TEXT PRIMARY KEY,
			org_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
			project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
			runtime_id TEXT,
			agent_id TEXT REFERENCES agents(id) ON DELETE SET NULL,
			target_service_id TEXT,
			target_service_name TEXT,
			target_service_type TEXT,
			type TEXT NOT NULL,
			status TEXT NOT NULL,
			body_hash TEXT NOT NULL,
			redacted_body JSONB NOT NULL DEFAULT '{}'::jsonb,
			idempotency_key TEXT NOT NULL,
			lease_owner_agent_id TEXT,
			lease_expires_at TIMESTAMPTZ,
			attempt_count INTEGER NOT NULL DEFAULT 0,
			max_attempts INTEGER NOT NULL DEFAULT 3,
			next_retry_at TIMESTAMPTZ,
			last_error_redacted TEXT,
			created_by TEXT,
			created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			expires_at TIMESTAMPTZ NOT NULL,
			UNIQUE (project_id, idempotency_key)
		)`,
		`CREATE INDEX IF NOT EXISTS relay_jobs_project_status_idx ON relay_jobs(project_id, status, created_at)`,
		`CREATE INDEX IF NOT EXISTS relay_jobs_retry_idx ON relay_jobs(project_id, status, next_retry_at)`,
		`CREATE TABLE IF NOT EXISTS relay_events (
			id TEXT PRIMARY KEY,
			org_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
			project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
			job_id TEXT NOT NULL REFERENCES relay_jobs(id) ON DELETE CASCADE,
			sequence BIGSERIAL,
			type TEXT NOT NULL,
			message_redacted TEXT NOT NULL,
			metadata_redacted JSONB NOT NULL DEFAULT '{}'::jsonb,
			created_at TIMESTAMPTZ NOT NULL DEFAULT now()
		)`,
		`CREATE INDEX IF NOT EXISTS relay_events_job_sequence_idx ON relay_events(job_id, sequence)`,
		`CREATE TABLE IF NOT EXISTS cloud_audit_events (
			id TEXT PRIMARY KEY,
			org_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
			project_id TEXT REFERENCES projects(id) ON DELETE SET NULL,
			actor_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
			actor_type TEXT NOT NULL,
			action TEXT NOT NULL,
			resource_type TEXT NOT NULL,
			resource_id TEXT NOT NULL,
			result TEXT NOT NULL,
			ip_address TEXT,
			user_agent TEXT,
			metadata_redacted JSONB NOT NULL DEFAULT '{}'::jsonb,
			created_at TIMESTAMPTZ NOT NULL DEFAULT now()
		)`,
		`CREATE INDEX IF NOT EXISTS cloud_audit_events_org_created_idx ON cloud_audit_events(org_id, created_at)`,
		`CREATE OR REPLACE FUNCTION prevent_cloud_audit_mutation() RETURNS trigger AS $$
		BEGIN
			RAISE EXCEPTION 'cloud_audit_events is append-only';
		END;
		$$ LANGUAGE plpgsql`,
		`DROP TRIGGER IF EXISTS cloud_audit_events_no_update ON cloud_audit_events`,
		`DROP TRIGGER IF EXISTS cloud_audit_events_no_delete ON cloud_audit_events`,
		`CREATE TRIGGER cloud_audit_events_no_update BEFORE UPDATE ON cloud_audit_events FOR EACH ROW EXECUTE FUNCTION prevent_cloud_audit_mutation()`,
		`CREATE TRIGGER cloud_audit_events_no_delete BEFORE DELETE ON cloud_audit_events FOR EACH ROW EXECUTE FUNCTION prevent_cloud_audit_mutation()`,
		`CREATE TABLE IF NOT EXISTS idempotency_keys (
			scope TEXT NOT NULL,
			key TEXT NOT NULL,
			resource_type TEXT NOT NULL,
			resource_id TEXT NOT NULL,
			created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			PRIMARY KEY (scope, key)
		)`,
		`CREATE TABLE IF NOT EXISTS personal_access_tokens (
			id TEXT PRIMARY KEY,
			user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			token_hash TEXT NOT NULL,
			expires_at TIMESTAMPTZ NOT NULL,
			revoked BOOLEAN NOT NULL DEFAULT false,
			created_at TIMESTAMPTZ NOT NULL DEFAULT now()
		)`,
		`ALTER TABLE personal_access_tokens ADD COLUMN IF NOT EXISTS purpose TEXT`,
		`CREATE INDEX IF NOT EXISTS personal_access_tokens_user_id_idx ON personal_access_tokens(user_id)`,
		`CREATE UNIQUE INDEX IF NOT EXISTS personal_access_tokens_user_purpose_idx ON personal_access_tokens(user_id, purpose) WHERE purpose IS NOT NULL`,
		`CREATE TABLE IF NOT EXISTS oauth_identities (
			id TEXT PRIMARY KEY,
			user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			provider TEXT NOT NULL,
			subject TEXT NOT NULL,
			created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
			UNIQUE (provider, subject),
			UNIQUE (user_id, provider)
		)`,
		`CREATE INDEX IF NOT EXISTS oauth_identities_user_idx ON oauth_identities(user_id)`,
		`CREATE TABLE IF NOT EXISTS cloud_admin_bootstrap_state (
			key TEXT PRIMARY KEY,
			user_id TEXT NOT NULL REFERENCES users(id),
			organization_id TEXT NOT NULL REFERENCES organizations(id),
			project_id TEXT NOT NULL REFERENCES projects(id),
			normalized_email TEXT NOT NULL,
			org_slug TEXT NOT NULL,
			project_slug TEXT NOT NULL,
			completed_at TIMESTAMPTZ NOT NULL,
			updated_at TIMESTAMPTZ NOT NULL
		)`,
		`CREATE TABLE IF NOT EXISTS otp_requests (
			id TEXT PRIMARY KEY,
			project_id TEXT NOT NULL,
			user_id TEXT NOT NULL,
			purpose TEXT NOT NULL,
			salt TEXT NOT NULL,
			code_hash TEXT NOT NULL,
			expires_at TIMESTAMPTZ NOT NULL,
			used_at TIMESTAMPTZ,
			created_at TIMESTAMPTZ NOT NULL DEFAULT now()
		)`,
		`CREATE INDEX IF NOT EXISTS otp_requests_user_created_idx ON otp_requests(user_id, created_at)`,
		`CREATE UNIQUE INDEX IF NOT EXISTS control_services_id_project_uidx ON control_services(id, project_id)`,
		`CREATE TABLE IF NOT EXISTS github_installations (
			installation_id BIGINT PRIMARY KEY CHECK (installation_id > 0),
			account_id BIGINT NOT NULL CHECK (account_id > 0),
			account_login TEXT NOT NULL,
			account_type TEXT NOT NULL,
			status TEXT NOT NULL CHECK (status IN ('active','suspended','deleted')),
			suspended BOOLEAN NOT NULL DEFAULT false,
			created_at TIMESTAMPTZ NOT NULL,
			updated_at TIMESTAMPTZ NOT NULL,
			CHECK ((status = 'suspended') = suspended)
		)`,
		`CREATE TABLE IF NOT EXISTS github_repositories (
			repository_id BIGINT PRIMARY KEY CHECK (repository_id > 0),
			installation_id BIGINT NOT NULL CHECK (installation_id > 0) REFERENCES github_installations(installation_id),
			owner_id BIGINT NOT NULL CHECK (owner_id > 0),
			owner_login TEXT NOT NULL,
			name TEXT NOT NULL,
			full_name TEXT NOT NULL,
			private BOOLEAN NOT NULL,
			archived BOOLEAN NOT NULL,
			disabled BOOLEAN NOT NULL,
			default_branch TEXT NOT NULL,
			status TEXT NOT NULL CHECK (status IN ('active','removed','deleted')),
			created_at TIMESTAMPTZ NOT NULL,
			updated_at TIMESTAMPTZ NOT NULL,
			UNIQUE (repository_id, installation_id)
		)`,
		`CREATE INDEX IF NOT EXISTS github_repositories_installation_idx ON github_repositories(installation_id, repository_id)`,
		`CREATE TABLE IF NOT EXISTS github_installation_project_links (
			installation_id BIGINT NOT NULL CHECK (installation_id > 0) REFERENCES github_installations(installation_id),
			project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
			claimed_by TEXT NOT NULL REFERENCES users(id),
			status TEXT NOT NULL CHECK (status IN ('active','revoked')),
			claimed_at TIMESTAMPTZ NOT NULL,
			revoked_at TIMESTAMPTZ,
			PRIMARY KEY (installation_id, project_id)
		)`,
		`CREATE INDEX IF NOT EXISTS github_installation_project_links_project_idx ON github_installation_project_links(project_id, installation_id) WHERE status = 'active'`,
		`CREATE TABLE IF NOT EXISTS github_repository_claims (
			repository_id BIGINT PRIMARY KEY CHECK (repository_id > 0),
			installation_id BIGINT NOT NULL CHECK (installation_id > 0),
			project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
			claimed_by TEXT NOT NULL REFERENCES users(id),
			status TEXT NOT NULL CHECK (status IN ('active','revoked')),
			claimed_at TIMESTAMPTZ NOT NULL,
			released_at TIMESTAMPTZ,
			UNIQUE (repository_id, installation_id, project_id),
			FOREIGN KEY (repository_id, installation_id) REFERENCES github_repositories(repository_id, installation_id)
		)`,
		`CREATE UNIQUE INDEX IF NOT EXISTS github_repository_claims_active_repository_uidx ON github_repository_claims(repository_id) WHERE status = 'active'`,
		`CREATE INDEX IF NOT EXISTS github_repository_claims_project_idx ON github_repository_claims(project_id, repository_id)`,
		`CREATE TABLE IF NOT EXISTS github_service_bindings (
			id TEXT PRIMARY KEY,
			project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
			service_id TEXT NOT NULL,
			repository_id BIGINT NOT NULL CHECK (repository_id > 0),
			installation_id BIGINT NOT NULL CHECK (installation_id > 0),
			service_key TEXT NOT NULL,
			config_path TEXT NOT NULL CHECK (config_path <> '' AND config_path !~ '^/'),
			status TEXT NOT NULL CHECK (status IN ('active','revoked')),
			created_by TEXT NOT NULL REFERENCES users(id),
			created_at TIMESTAMPTZ NOT NULL,
			updated_at TIMESTAMPTZ NOT NULL,
			removed_at TIMESTAMPTZ,
			FOREIGN KEY (service_id, project_id) REFERENCES control_services(id, project_id) ON DELETE CASCADE,
			FOREIGN KEY (repository_id, installation_id) REFERENCES github_repositories(repository_id, installation_id)
		)`,
		`CREATE UNIQUE INDEX IF NOT EXISTS github_service_bindings_active_service_uidx ON github_service_bindings(service_id) WHERE status = 'active'`,
		`CREATE UNIQUE INDEX IF NOT EXISTS github_service_bindings_active_repository_key_uidx ON github_service_bindings(repository_id, service_key) WHERE status = 'active'`,
		`CREATE INDEX IF NOT EXISTS github_service_bindings_project_idx ON github_service_bindings(project_id, created_at)`,
		`CREATE TABLE IF NOT EXISTS github_webhook_deliveries (
			delivery_id TEXT PRIMARY KEY CHECK (delivery_id <> ''),
			event TEXT NOT NULL,
			action TEXT NOT NULL,
			installation_id BIGINT CHECK (installation_id > 0),
			repository_id BIGINT CHECK (repository_id > 0),
			received_at TIMESTAMPTZ NOT NULL,
			processed_at TIMESTAMPTZ NOT NULL
		)`,
	}
	for _, statement := range statements {
		if _, err := db.ExecContext(ctx, statement); err != nil {
			return err
		}
	}
	if err := MigrateBootstrapCheckpoint(ctx, db); err != nil {
		return err
	}
	return MigrateBuildRecords(ctx, db)
}
