agent_addr: 127.0.0.1:9443
sync_state_path: ""
tls:
  ca_cert_path: ./certs/ca.crt
  client_cert_path: ./certs/client.crt
  client_key_path: ./certs/client.key
  pinned_server_cert_sha256: ""
  server_name: localhost
