"use client";

import { useMemo, useState } from "react";
import { Empty, StatusBadge } from "@/components/ui/primitives";
import type { ConsoleController } from "@/features/console/types";
import { PlacementDialog } from "@/features/infrastructure/placement-dialog";
import { useInfrastructureData } from "@/features/infrastructure/data";
import { bootstrapProgress, buildTopologyGraph, capacityLabel, layoutTopology } from "@/lib/presentation/infrastructure/model";

export function InfrastructureView({ console }: { console: ConsoleController }) {
  const { data, source, error, load } = useInfrastructureData(console);
  const [placementOpen, setPlacementOpen] = useState(false);
  const [bootstrapOpen, setBootstrapOpen] = useState(false);
  if (!console.state.project) return <Empty text="Select a project first." />;
  if (source === "loading" && !data.facts) return <Empty title="Loading infrastructure…" text="Reading factual topology and runtime inventory from Local API." />;
  if (!data.facts) return <Empty title="Infrastructure unavailable" text={error || "Local API did not return topology facts."} action={<button onClick={() => void load()} type="button">Retry</button>} />;

  return <div className="infrastructurePage">
    <div className="destinationToolbar"><p>{error || "Cloud topology facts remain visible when Agent runtime data is unavailable."}</p><button onClick={() => console.route.tab === "bootstrap" ? setBootstrapOpen(true) : setPlacementOpen(true)} type="button">{console.route.tab === "bootstrap" ? "Add server" : "Plan placement"}</button></div>
    {console.route.tab === "topology" ? <TopologyTab console={console} facts={data.facts} topology={data.topology} /> : null}
    {console.route.tab === "runtimes" ? <RuntimesTab console={console} facts={data.facts} topology={data.topology} /> : null}
    {console.route.tab === "nodes" ? <NodesTab console={console} facts={data.facts} /> : null}
    {console.route.tab === "bootstrap" ? <BootstrapTab console={console} /> : null}
    {placementOpen ? <PlacementDialog console={console} data={{ facts: data.facts, topology: data.topology, repositories: data.repositories, bindings: data.bindings, builds: data.builds, policies: data.policies }} onApplied={() => void load()} onClose={() => setPlacementOpen(false)} /> : null}
    {bootstrapOpen ? <BootstrapDialog console={console} onClose={() => setBootstrapOpen(false)} /> : null}
  </div>;
}

function TopologyTab({ console, facts, topology }: { console: ConsoleController; facts: NonNullable<ReturnType<typeof useInfrastructureData>["data"]["facts"]>; topology: ReturnType<typeof useInfrastructureData>["data"]["topology"] }) {
  const graph = useMemo(() => buildTopologyGraph(facts, topology), [facts, topology]);
  const positioned = useMemo(() => layoutTopology(graph.nodes), [graph.nodes]);
  const selectedID = console.route.topology || positioned[0]?.id || "";
  const selected = positioned.find((item) => item.id === selectedID);
  const byID = new Map(positioned.map((item) => [item.id, item]));
  const height = Math.max(280, ...positioned.map((item) => item.y + 112));
  const unassigned = facts.services.filter((service) => !topology?.assignments.some((item) => item.service_key === service.key));
  return <section aria-labelledby="topology-heading">
    <div className="sectionHeading"><div><h2 id="topology-heading">Factual topology</h2><p>Environment → runtime → node/Agent and exact service assignment edges.</p></div><span className="sourceTag">{topology ? `TopologyPlan r${topology.revision}` : "No TopologyPlan"}</span></div>
    {!topology ? <div className="truthCallout"><b>No topology plan</b><p>Infrastructure facts are shown without service placement edges. Service inventory is not used to fabricate assignments.</p></div> : null}
    <div className="topologyCanvas" style={{ height }}>
      <svg aria-hidden="true" className="topologyEdges" height={height} width="100%"><defs><marker id="topology-arrow" markerHeight="7" markerWidth="7" orient="auto" refX="6" refY="3.5"><path d="M0,0 L7,3.5 L0,7 z" /></marker></defs>{graph.edges.map((edge) => { const from = byID.get(edge.from); const to = byID.get(edge.to); return from && to ? <line key={`${edge.from}-${edge.to}-${edge.relation}`} markerEnd="url(#topology-arrow)" x1={from.x + 176} x2={to.x} y1={from.y + 31} y2={to.y + 31} /> : null; })}</svg>
      {positioned.map((node) => <button aria-pressed={selectedID === node.id} className="topologyNode" key={node.id} onClick={() => console.navigate({ topology: node.id })} style={{ left: node.x, top: node.y }} type="button"><span>{node.kind}</span><strong>{node.label}</strong><StatusBadge value={node.status} /><small>{node.detail}</small></button>)}
    </div>
    <div className="topologyTree" aria-label="Topology relationship list">{facts.environments.map((environment) => <section key={environment.id}><h3>{environment.name}</h3>{facts.runtimes.filter((runtime) => runtime.environment_id === environment.id).map((runtime) => <div key={runtime.id}><b>{runtime.name}</b><p>Nodes: {facts.nodes.filter((node) => node.runtime_id === runtime.id).map((node) => node.id).join(", ") || "none"}</p><p>Agents: {facts.agents.filter((agent) => agent.runtime_id === runtime.id).map((agent) => agent.id).join(", ") || "none"}</p><p>Services: {topology?.assignments.filter((assignment) => assignment.runtime_id === runtime.id).map((assignment) => assignment.service_key).join(", ") || "none assigned"}</p></div>)}</section>)}</div>
    <div className="infrastructureSplit"><section><h3>Relationship evidence</h3><ul className="relationshipList">{graph.edges.map((edge) => <li key={`${edge.from}-${edge.to}-${edge.relation}`}><code>{edge.from}</code><span>→</span><code>{edge.to}</code><small>{edge.relation}</small></li>)}</ul></section><aside className="inspector"><h3>{selected?.label || "Select a node"}</h3>{selected ? <><StatusBadge value={selected.status} /><p>{selected.detail}</p><code>{selected.id}</code></> : null}{graph.unresolved.length ? <><h4>Unresolved</h4>{graph.unresolved.map((item) => <p key={`${item.id}-${item.reason}`}><b>{item.label}</b> — {item.reason}</p>)}</> : null}{unassigned.length ? <><h4>Unassigned services</h4><p>{unassigned.map((item) => item.key).join(", ")}</p></> : null}</aside></div>
  </section>;
}

function RuntimesTab({ console, facts, topology }: { console: ConsoleController; facts: NonNullable<ReturnType<typeof useInfrastructureData>["data"]["facts"]>; topology: ReturnType<typeof useInfrastructureData>["data"]["topology"] }) {
  const selected = facts.runtimes.find((item) => item.id === console.route.runtime) ?? facts.runtimes[0];
  return <div className="masterDetail infrastructureMaster"><section className="masterList"><div className="sectionHeading"><h2>Runtimes</h2><span>{facts.runtimes.length} factual records</span></div>{facts.runtimes.length ? <ul>{facts.runtimes.map((runtime) => { const nodes = facts.nodes.filter((item) => item.runtime_id === runtime.id); const agents = facts.agents.filter((item) => item.runtime_id === runtime.id && item.status === "active"); const assignments = topology?.assignments.filter((item) => item.runtime_id === runtime.id) ?? []; return <li key={runtime.id}><button aria-pressed={selected?.id === runtime.id} onClick={() => console.navigate({ runtime: runtime.id })} type="button"><span><strong>{runtime.name}</strong><small>{facts.environments.find((item) => item.id === runtime.environment_id)?.name || runtime.environment_id} · {runtime.type}</small><small>{nodes.length} nodes · {agents.length} active Agents · {assignments.length} services</small></span><StatusBadge value={runtime.status} /></button></li>; })}</ul> : <Empty text="No runtime inventory exists." />}</section><section className="detailPanel">{selected ? <><div className="detailHeading"><div><p className="eyebrow">Runtime detail</p><h2>{selected.name}</h2></div><StatusBadge value={selected.status} /></div><dl className="evidenceGrid"><Fact label="Canonical ID" value={selected.id} /><Fact label="Environment" value={facts.environments.find((item) => item.id === selected.environment_id)?.name || selected.environment_id} /><Fact label="Type" value={selected.type} /><Fact label="Capacity coverage" value={runtimeCapacity(facts, selected.id)} /></dl><Related title="Nodes" values={facts.nodes.filter((item) => item.runtime_id === selected.id).map((item) => `${item.id} · ${item.status}`)} /><Related title="Agents" values={facts.agents.filter((item) => item.runtime_id === selected.id).map((item) => `${item.id} · ${item.status} · ${item.last_seen_at || "last seen unknown"}`)} /><Related title="Assignments" values={(topology?.assignments ?? []).filter((item) => item.runtime_id === selected.id).map((item) => `${item.service_key} · ${item.replicas} replicas`)} /></> : <Empty text="Select a runtime." />}</section></div>;
}

function NodesTab({ console, facts }: { console: ConsoleController; facts: NonNullable<ReturnType<typeof useInfrastructureData>["data"]["facts"]> }) {
  const selected = console.state.nodes.find((item) => item.id === console.route.node) ?? console.state.nodes[0];
  const unavailable = console.session?.agent_connected !== "ok";
  return <div className="masterDetail infrastructureMaster"><section className="masterList"><div className="sectionHeading"><h2>Nodes</h2><span>{console.state.nodes.length} records</span></div>{unavailable ? <p className="truthCallout">Agent source unavailable. Inventory remains visible; node mutations are disabled.</p> : null}<ul>{console.state.nodes.map((node) => <li key={node.id}><button aria-pressed={selected?.id === node.id} onClick={() => { console.navigate({ node: node.id }); void console.actions.diagnostics(node.id); }} type="button"><span><strong>{node.name}</strong><small>{facts.runtimes.find((runtime) => facts.nodes.some((item) => item.id === node.id && item.runtime_id === runtime.id))?.name || "Runtime unresolved"} · {node.role}</small><small>{node.agent_version || "Agent version unavailable"} · {node.last_seen_at || "last seen unknown"}</small></span><StatusBadge value={node.status} /></button></li>)}</ul></section><section className="detailPanel">{selected ? <><div className="detailHeading"><div><p className="eyebrow">Node detail</p><h2>{selected.name}</h2></div><StatusBadge value={selected.status} /></div><dl className="evidenceGrid"><Fact label="Canonical ID" value={selected.id} /><Fact label="Provider / region" value={[selected.provider, selected.region].filter(Boolean).join(" / ") || "Not reported"} /><Fact label="Capacity" value={`${capacityLabel(selected.cpu_cores, selected.memory_mb)} · disk ${selected.disk_total_gb === undefined ? "Unknown" : `${selected.disk_total_gb} GiB`}`} /><Fact label="K3s" value={selected.k3s_status || selected.k3s_role || "Not reported"} /><Fact label="Agent" value={[selected.agent_id, selected.agent_version].filter(Boolean).join(" · ") || "Unavailable"} /><Fact label="Heartbeat" value={selected.last_seen_at || "Not reported"} /></dl><Related title="Diagnostics" values={(console.state.nodeDetail?.open_bootstrap_events ?? []).map((item) => `${item.step}: ${item.message_redacted}`)} /><Related title="Recent deployment jobs" values={(console.state.nodeDetail?.recent_deployment_jobs ?? []).map((item) => `${item.id} · ${item.status}`)} /><div className="detailActions"><button disabled={unavailable} onClick={() => console.actions.nodeAction(selected.id, "offline")} type="button">Mark offline</button><button disabled={unavailable} onClick={() => console.actions.nodeAction(selected.id, "drain")} type="button">Drain</button><button className="danger" disabled={unavailable} onClick={() => console.actions.nodeAction(selected.id, "remove")} type="button">Remove…</button></div></> : <Empty text="No node inventory exists." />}</section></div>;
}

function BootstrapTab({ console }: { console: ConsoleController }) {
  const selected = console.state.sessions.find((item) => item.id === console.route.session) ?? console.state.sessions[0];
  const progress = bootstrapProgress(selected?.checkpoint, selected ? console.state.bootstrapEvents.length : 0);
  return <div className="bootstrapLayout"><section className="bootstrapInventory"><div className="sectionHeading"><div><h2>Bootstrap sessions</h2><p>Durable Cloud worker sessions; no public DNS assumption.</p></div></div>{console.state.sessions.length ? <ul>{console.state.sessions.map((session) => <li key={session.id}><button aria-pressed={selected?.id === session.id} onClick={() => { console.navigate({ session: session.id }); void console.actions.loadBootstrapEvents(session.id); }} type="button"><span><strong>{session.public_host || session.id}</strong><small>{session.role} · attempt {session.attempt_count ?? "?"}/{session.max_attempts ?? "?"}</small></span><StatusBadge value={session.status} /></button></li>)}</ul> : <Empty title="No bootstrap sessions" text="Use Add server to review connection input and create a Local API bootstrap session." />}</section><section className="bootstrapDetail">{selected ? <><div className="detailHeading"><div><p className="eyebrow">Selected session</p><h2>{selected.id}</h2></div><StatusBadge value={selected.status} /></div><dl className="evidenceGrid"><Fact label="Attempt" value={`${selected.attempt_count ?? "Unknown"}/${selected.max_attempts ?? "Unknown"}`} /><Fact label="Progress" value={progress.percent === null ? progress.label : `${progress.percent}% · ${progress.label}`} /><Fact label="Next step" value={selected.checkpoint ? `Step ${selected.checkpoint.next_step_index}` : "Not reported"} /><Fact label="Failure" value={selected.last_failure_message_redacted || selected.last_failure_code || "None reported"} /></dl><ol className="eventTimeline">{console.state.bootstrapEvents.map((event) => <li key={event.id}><span aria-hidden="true" /><div><b>{event.step}</b><p>{event.message_redacted}</p><small>{event.created_at}</small></div></li>)}</ol><button disabled={!['failed', 'dead_letter'].includes(selected.status)} onClick={() => console.actions.retryBootstrap(selected.id)} type="button">Retry eligible session</button></> : <Empty text="Select a bootstrap session." />}</section></div>;
}

function BootstrapDialog({ console, onClose }: { console: ConsoleController; onClose: () => void }) { return <dialog className="placementDialog" open aria-labelledby="bootstrap-title"><div className="dialogHeading"><div><p className="eyebrow">Bootstrap action</p><h2 id="bootstrap-title">Add server</h2><p>Review input before the canonical Local API session is created.</p></div><button aria-label="Close add server dialog" className="iconButton" onClick={onClose} type="button">×</button></div><form className="form placementForm" onSubmit={(event) => { void console.actions.addServer(event); onClose(); }}><label>Role<select className="select" name="role" required><option value="">Choose role…</option><option value="first_server">First server</option><option value="worker">Worker</option></select></label><label>SSH host or IP<input autoComplete="off" className="field" name="public_host" placeholder="203.0.113.10…" required /></label><label>SSH port<input className="field" inputMode="numeric" min="1" name="ssh_port" required type="number" /></label><label>SSH username<input autoComplete="username" className="field" name="ssh_username" required spellCheck={false} /></label><label>Authentication<select className="select" name="auth_method" required><option value="">Choose method…</option><option value="password">Password</option><option value="private_key">Private key</option></select></label><label className="span2">One-time credential<textarea autoComplete="off" className="textarea" name="secret" required /></label><p className="notice span2">Credential is submitted once, never stored in browser storage, and removed after worker handoff.</p><div className="dialogActions span2"><button onClick={onClose} type="button">Cancel</button><button type="submit">Review bootstrap request</button></div></form></dialog>; }

function Fact({ label, value }: { label: string; value: string }) { return <div><dt>{label}</dt><dd>{value}</dd></div>; }
function Related({ title, values }: { title: string; values: string[] }) { return <section><h3>{title}</h3>{values.length ? <ul className="compactList">{values.map((value) => <li key={value}>{value}</li>)}</ul> : <p className="muted">None reported.</p>}</section>; }
function runtimeCapacity(facts: NonNullable<ReturnType<typeof useInfrastructureData>["data"]["facts"]>, runtimeID: string) { const nodes = facts.nodes.filter((item) => item.runtime_id === runtimeID); return nodes.length && nodes.every((item) => item.cpu_cores !== undefined && item.memory_mb !== undefined) ? nodes.map((item) => capacityLabel(item.cpu_cores, item.memory_mb)).join(" · ") : "Unknown"; }
