package repository

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRenderConfigGoldenAndDeterministic(t *testing.T) {
	options := ConfigOptions{ServiceKey: "api", Context: ".", Dockerfile: "Dockerfile", Platform: "linux/amd64", Branch: "main", PreviewPRs: false}
	first, err := RenderConfig(options)
	if err != nil {
		t.Fatal(err)
	}
	second, err := RenderConfig(options)
	if err != nil {
		t.Fatal(err)
	}
	expected := `# Generated by opsi init. Review before committing.
apiVersion: cd.opsi.dev/v1alpha1
kind: ServiceBuild
metadata:
  serviceKey: api
build:
  context: .
  dockerfile: Dockerfile
  platforms:
    - linux/amd64
deploy:
  production:
    branches:
      - main
  preview:
    pullRequests: false
`
	if string(first) != expected || string(second) != expected {
		t.Fatalf("config mismatch:\n%s", first)
	}
	for _, forbidden := range []string{"project_id", "service_id", "repository_id", "installation_id", "cloud_url", "PAT", "token", "password", "private_key"} {
		if strings.Contains(string(first), forbidden) {
			t.Fatalf("config contains forbidden value %q", forbidden)
		}
	}
}

func TestValidateBuildInputs(t *testing.T) {
	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, "Dockerfile"), []byte("FROM scratch\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := ValidateBuildInputs(root, ".", "Dockerfile", "linux/amd64", "main"); err != nil {
		t.Fatal(err)
	}
	if err := ValidateBuildInputs(root, ".", "missing", "linux/amd64", "main"); err == nil {
		t.Fatal("missing Dockerfile accepted")
	}
	if err := ValidateBuildInputs(root, "../outside", "Dockerfile", "linux/amd64", "main"); err == nil {
		t.Fatal("outside context accepted")
	}
	if err := ValidateBuildInputs(root, ".", "Dockerfile", "linux/arm64", "main"); err == nil {
		t.Fatal("unsupported platform accepted")
	}
	if err := ValidateBuildInputs(root, ".", "Dockerfile", "linux/amd64", "bad branch"); err == nil {
		t.Fatal("unsafe branch accepted")
	}
	outside := t.TempDir()
	if err := os.WriteFile(filepath.Join(outside, "Dockerfile"), []byte("FROM scratch\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(filepath.Join(outside, "Dockerfile"), filepath.Join(root, "EscapeDockerfile")); err != nil {
		t.Fatal(err)
	}
	if err := ValidateBuildInputs(root, ".", "EscapeDockerfile", "linux/amd64", "main"); err == nil {
		t.Fatal("symlink escape accepted")
	}
}

func TestPathAndServiceKeyValidation(t *testing.T) {
	for _, key := range []string{"api", "a", "api_v1", "api-v1"} {
		if err := ValidateServiceKey(key); err != nil {
			t.Fatalf("valid key %q: %v", key, err)
		}
	}
	for _, key := range []string{"", "API", "-api", "api-", strings.Repeat("a", 64)} {
		if err := ValidateServiceKey(key); err == nil {
			t.Fatalf("invalid key accepted: %q", key)
		}
	}
	if err := ValidateConfigPath(".opsi/opsi-cd.yaml"); err != nil {
		t.Fatal(err)
	}
	if err := ValidateWorkflowPath(".github/workflows/opsi-cd.yaml"); err != nil {
		t.Fatal(err)
	}
	for _, value := range []string{"/absolute", "../escape", ".opsi", ".opsi//bad", `.opsi\bad`} {
		if err := ValidateConfigPath(value); err == nil {
			t.Fatalf("invalid config path accepted: %q", value)
		}
	}
	for _, value := range []string{"workflow.yaml", ".github/workflows", ".github/workflows/../bad"} {
		if err := ValidateWorkflowPath(value); err == nil {
			t.Fatalf("invalid workflow path accepted: %q", value)
		}
	}
}
