package repository

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"unicode"

	"gopkg.in/yaml.v3"
)

const configComment = "# Generated by opsi init. Review before committing.\n"

var serviceKeyPattern = regexp.MustCompile(`^[a-z0-9](?:[a-z0-9_-]{0,61}[a-z0-9])?$`)
var platformPattern = regexp.MustCompile(`^[a-z0-9][a-z0-9._-]*/[a-z0-9][a-z0-9._-]*(?:/[a-z0-9][a-z0-9._-]*)?$`)

// ConfigOptions is the compatibility input used by opsi init. It renders one
// service in the v2 repository contract.
type ConfigOptions struct {
	ServiceKey string
	Context    string
	Dockerfile string
	Platform   string
	Branch     string
	PreviewPRs bool
}

type ConfigV2 struct {
	Version  int         `json:"version" yaml:"version"`
	Services []ServiceV2 `json:"services" yaml:"services"`
}

type ServiceV2 struct {
	Key          string   `json:"key" yaml:"key"`
	Build        BuildV2  `json:"build" yaml:"build"`
	WatchPaths   []string `json:"watch_paths" yaml:"watchPaths"`
	SharedPaths  []string `json:"shared_paths" yaml:"sharedPaths"`
	Dependencies []string `json:"dependencies" yaml:"dependencies"`
	Deploy       DeployV2 `json:"deploy" yaml:"deploy"`
}

type BuildV2 struct {
	Context    string `json:"context" yaml:"context"`
	Dockerfile string `json:"dockerfile" yaml:"dockerfile"`
	Platform   string `json:"platform" yaml:"platform"`
}

type DeployV2 struct {
	Production ProductionV2 `json:"production" yaml:"production"`
	Preview    PreviewV2    `json:"preview" yaml:"preview"`
}

type ProductionV2 struct {
	Enabled  bool     `json:"enabled" yaml:"enabled"`
	Branches []string `json:"branches" yaml:"branches"`
}

type PreviewV2 struct {
	Enabled      bool `json:"enabled" yaml:"enabled"`
	PullRequests bool `json:"pull_requests" yaml:"pullRequests"`
}

func ValidateServiceKey(value string) error {
	if len(value) < 1 || len(value) > 63 || !serviceKeyPattern.MatchString(value) {
		return errors.New("service key must be 1-63 lowercase ASCII characters with alphanumeric ends and only '-', '_' inside")
	}
	return nil
}

func ValidateConfigPath(value string) error   { return validateManagedPath(value, ".opsi") }
func ValidateWorkflowPath(value string) error { return validateManagedPath(value, ".github/workflows") }

func validateManagedPath(value, prefix string) error {
	if err := validateSlashRelativePath(value, false); err != nil {
		return err
	}
	if value == prefix || !strings.HasPrefix(value, prefix+"/") {
		return fmt.Errorf("path must be inside %s/", prefix)
	}
	return nil
}

func ValidateBuildInputs(repoRoot, contextPath, dockerfilePath, platform, branch string) error {
	if err := validatePlatform(platform); err != nil {
		return err
	}
	if err := validateSlashRelativePath(contextPath, true); err != nil {
		return fmt.Errorf("invalid build context: %w", err)
	}
	if err := validateSlashRelativePath(dockerfilePath, false); err != nil {
		return fmt.Errorf("invalid Dockerfile path: %w", err)
	}
	if err := ValidateBranch(branch); err != nil {
		return err
	}
	root, err := filepath.EvalSymlinks(repoRoot)
	if err != nil {
		return fmt.Errorf("resolve repository root: %w", err)
	}
	contextResolved, err := filepath.EvalSymlinks(filepath.Join(root, filepath.FromSlash(contextPath)))
	if err != nil {
		return fmt.Errorf("resolve build context: %w", err)
	}
	if err := ensureInside(root, contextResolved); err != nil {
		return fmt.Errorf("build context: %w", err)
	}
	contextInfo, err := os.Stat(contextResolved)
	if err != nil || !contextInfo.IsDir() {
		return errors.New("build context must be an existing directory")
	}
	dockerfileResolved, err := filepath.EvalSymlinks(filepath.Join(root, filepath.FromSlash(dockerfilePath)))
	if err != nil {
		return fmt.Errorf("resolve Dockerfile: %w", err)
	}
	if err := ensureInside(root, dockerfileResolved); err != nil {
		return fmt.Errorf("Dockerfile: %w", err)
	}
	dockerfileInfo, err := os.Stat(dockerfileResolved)
	if err != nil || !dockerfileInfo.Mode().IsRegular() {
		return errors.New("Dockerfile must be an existing regular file")
	}
	return nil
}

func ValidateBranch(value string) error {
	if value == "" || value == "@" || strings.HasPrefix(value, "-") || strings.HasSuffix(value, ".") || strings.HasSuffix(value, "/") {
		return errors.New("production branch is not a valid Git ref name")
	}
	if strings.Contains(value, "..") || strings.Contains(value, "@{") || strings.Contains(value, "//") || strings.IndexAny(value, " ~^:?*[\\") >= 0 || strings.IndexFunc(value, unicode.IsControl) >= 0 {
		return errors.New("production branch is not a valid Git ref name")
	}
	for _, segment := range strings.Split(value, "/") {
		if segment == "" || strings.HasPrefix(segment, ".") || strings.HasSuffix(segment, ".lock") {
			return errors.New("production branch is not a valid Git ref name")
		}
	}
	return nil
}

func validatePlatform(value string) error {
	if value != "linux/amd64" || !platformPattern.MatchString(value) {
		return errors.New("R5-006 supports only linux/amd64")
	}
	return nil
}

func RenderConfig(options ConfigOptions) ([]byte, error) {
	if err := ValidateServiceKey(options.ServiceKey); err != nil {
		return nil, err
	}
	if err := ValidateBranch(options.Branch); err != nil {
		return nil, err
	}
	return RenderConfigV2(ConfigV2{
		Version: 2,
		Services: []ServiceV2{{
			Key:          options.ServiceKey,
			Build:        BuildV2{Context: options.Context, Dockerfile: options.Dockerfile, Platform: options.Platform},
			WatchPaths:   []string{},
			SharedPaths:  []string{},
			Dependencies: []string{},
			Deploy: DeployV2{
				Production: ProductionV2{Enabled: true, Branches: []string{options.Branch}},
				Preview:    PreviewV2{Enabled: options.PreviewPRs, PullRequests: options.PreviewPRs},
			},
		}},
	})
}

func RenderConfigV2(cfg ConfigV2) ([]byte, error) {
	if err := ValidateConfig("", &cfg); err != nil {
		return nil, err
	}
	cfg = canonicalConfig(cfg)
	var output bytes.Buffer
	encoder := yaml.NewEncoder(&output)
	encoder.SetIndent(2)
	if err := encoder.Encode(cfg); err != nil {
		return nil, fmt.Errorf("render repository config: %w", err)
	}
	if err := encoder.Close(); err != nil {
		return nil, fmt.Errorf("finish repository config: %w", err)
	}
	return append([]byte(configComment), output.Bytes()...), nil
}

func ValidateConfig(repoRoot string, cfg *ConfigV2) error {
	if cfg == nil || cfg.Version != 2 {
		return errors.New("config version must be 2")
	}
	if len(cfg.Services) == 0 || len(cfg.Services) > 128 {
		return errors.New("config must contain 1-128 services")
	}
	seen := map[string]bool{}
	for i := range cfg.Services {
		s := &cfg.Services[i]
		if err := ValidateServiceKey(s.Key); err != nil {
			return fmt.Errorf("service %q: %w", s.Key, err)
		}
		if seen[s.Key] {
			return fmt.Errorf("duplicate service key %q", s.Key)
		}
		seen[s.Key] = true
		if err := validatePlatform(s.Build.Platform); err != nil {
			return fmt.Errorf("service %s: %w", s.Key, err)
		}
		if err := validateSlashRelativePath(s.Build.Context, true); err != nil {
			return fmt.Errorf("service %s context: %w", s.Key, err)
		}
		if err := validateSlashRelativePath(s.Build.Dockerfile, false); err != nil {
			return fmt.Errorf("service %s Dockerfile: %w", s.Key, err)
		}
		if len(s.WatchPaths) > 64 || len(s.SharedPaths) > 64 || len(s.Dependencies) > 64 || len(s.Deploy.Production.Branches) > 64 {
			return fmt.Errorf("service %s exceeds a 64-entry list limit", s.Key)
		}
		if duplicate := firstDuplicate(s.WatchPaths); duplicate != "" {
			return fmt.Errorf("service %s has duplicate watch path %q", s.Key, duplicate)
		}
		if duplicate := firstDuplicate(s.SharedPaths); duplicate != "" {
			return fmt.Errorf("service %s has duplicate shared path %q", s.Key, duplicate)
		}
		if duplicate := firstDuplicate(s.Dependencies); duplicate != "" {
			return fmt.Errorf("service %s has duplicate dependency %q", s.Key, duplicate)
		}
		if duplicate := firstDuplicate(s.Deploy.Production.Branches); duplicate != "" {
			return fmt.Errorf("service %s has duplicate production branch %q", s.Key, duplicate)
		}
		for _, p := range append(append([]string{}, s.WatchPaths...), s.SharedPaths...) {
			if err := validateSlashRelativePath(p, true); err != nil {
				return fmt.Errorf("service %s path: %w", s.Key, err)
			}
			if repoRoot != "" {
				if err := validatePathSymlinks(repoRoot, p); err != nil {
					return fmt.Errorf("service %s path %s: %w", s.Key, p, err)
				}
			}
		}
		if repoRoot != "" {
			if err := validatePathSymlinks(repoRoot, s.Build.Context); err != nil {
				return fmt.Errorf("service %s context: %w", s.Key, err)
			}
			if err := validatePathSymlinks(repoRoot, s.Build.Dockerfile); err != nil {
				return fmt.Errorf("service %s Dockerfile: %w", s.Key, err)
			}
		}
		if s.Deploy.Production.Enabled && len(s.Deploy.Production.Branches) == 0 {
			return fmt.Errorf("service %s production intent requires a branch", s.Key)
		}
		if !s.Deploy.Production.Enabled && len(s.Deploy.Production.Branches) > 0 {
			return fmt.Errorf("service %s disabled production intent must not contain branches", s.Key)
		}
		for _, branch := range s.Deploy.Production.Branches {
			if err := ValidateBranch(branch); err != nil {
				return fmt.Errorf("service %s: %w", s.Key, err)
			}
		}
		if s.Deploy.Preview.PullRequests != s.Deploy.Preview.Enabled {
			return fmt.Errorf("service %s preview enabled must match pullRequests intent", s.Key)
		}
	}
	for _, s := range cfg.Services {
		for _, dep := range s.Dependencies {
			if dep == s.Key || !seen[dep] {
				return fmt.Errorf("service %s has invalid dependency %q", s.Key, dep)
			}
		}
	}
	if cycle := dependencyCycle(*cfg); cycle != "" {
		return fmt.Errorf("service dependency cycle: %s", cycle)
	}
	if repoRoot != "" {
		if root, err := filepath.EvalSymlinks(repoRoot); err != nil {
			return fmt.Errorf("resolve repository root: %w", err)
		} else if err := ensureInside(root, root); err != nil {
			return err
		}
	}
	return nil
}

func validatePathSymlinks(root, relative string) error {
	resolvedRoot, err := filepath.EvalSymlinks(root)
	if err != nil {
		return err
	}
	current := resolvedRoot
	for _, segment := range strings.Split(relative, "/") {
		if segment == "." {
			continue
		}
		current = filepath.Join(current, segment)
		info, statErr := os.Lstat(current)
		if errors.Is(statErr, os.ErrNotExist) {
			break
		}
		if statErr != nil {
			return statErr
		}
		if info.Mode()&os.ModeSymlink != 0 {
			target, err := filepath.EvalSymlinks(current)
			if err != nil {
				return err
			}
			if err := ensureInside(resolvedRoot, target); err != nil {
				return err
			}
		}
	}
	return nil
}

func canonicalConfig(cfg ConfigV2) ConfigV2 {
	cfg.Version = 2
	sort.Slice(cfg.Services, func(i, j int) bool { return cfg.Services[i].Key < cfg.Services[j].Key })
	for i := range cfg.Services {
		s := &cfg.Services[i]
		s.WatchPaths = uniqueSorted(s.WatchPaths)
		s.SharedPaths = uniqueSorted(s.SharedPaths)
		s.Dependencies = uniqueSorted(s.Dependencies)
		s.Deploy.Production.Branches = uniqueSorted(s.Deploy.Production.Branches)
		if s.WatchPaths == nil {
			s.WatchPaths = []string{}
		}
		if s.SharedPaths == nil {
			s.SharedPaths = []string{}
		}
		if s.Dependencies == nil {
			s.Dependencies = []string{}
		}
		if s.Deploy.Production.Branches == nil {
			s.Deploy.Production.Branches = []string{}
		}
	}
	return cfg
}

func uniqueSorted(values []string) []string {
	out := append([]string(nil), values...)
	sort.Strings(out)
	result := out[:0]
	for _, v := range out {
		if len(result) == 0 || result[len(result)-1] != v {
			result = append(result, v)
		}
	}
	return result
}

func firstDuplicate(values []string) string {
	seen := map[string]bool{}
	for _, value := range values {
		if seen[value] {
			return value
		}
		seen[value] = true
	}
	return ""
}

func dependencyCycle(cfg ConfigV2) string {
	state := map[string]int{}
	stack := []string{}
	var visit func(string) string
	visit = func(key string) string {
		state[key] = 1
		stack = append(stack, key)
		var svc ServiceV2
		for _, candidate := range cfg.Services {
			if candidate.Key == key {
				svc = candidate
				break
			}
		}
		for _, dep := range svc.Dependencies {
			if state[dep] == 1 {
				return dep
			}
			if state[dep] == 0 {
				if cycle := visit(dep); cycle != "" {
					return cycle
				}
			}
		}
		stack = stack[:len(stack)-1]
		state[key] = 2
		return ""
	}
	for _, svc := range cfg.Services {
		if state[svc.Key] == 0 {
			if cycle := visit(svc.Key); cycle != "" {
				return cycle
			}
		}
	}
	return ""
}

func UpsertService(cfg ConfigV2, service ServiceV2) (ConfigV2, error) {
	if err := ValidateServiceKey(service.Key); err != nil {
		return ConfigV2{}, err
	}
	found := false
	for i := range cfg.Services {
		if cfg.Services[i].Key == service.Key {
			cfg.Services[i] = service
			found = true
			break
		}
	}
	if !found {
		cfg.Services = append(cfg.Services, service)
	}
	if err := ValidateConfig("", &cfg); err != nil {
		return ConfigV2{}, err
	}
	return canonicalConfig(cfg), nil
}

func ConfigHash(data []byte) string { sum := sha256.Sum256(data); return hex.EncodeToString(sum[:]) }

func (s ServiceV2) Paths() []string {
	return append(append([]string{s.Build.Context, s.Build.Dockerfile}, s.WatchPaths...), s.SharedPaths...)
}

func validateSlashRelativePath(value string, allowDot bool) error {
	if value == "" || len(value) > 512 || strings.Contains(value, "\\") || strings.IndexFunc(value, unicode.IsControl) >= 0 || path.IsAbs(value) || filepath.IsAbs(value) {
		return errors.New("path must be a 1-512 byte slash-separated relative path")
	}
	if allowDot && value == "." {
		return nil
	}
	if path.Clean(value) != value {
		return errors.New("path must not contain empty, dot, or parent segments")
	}
	for _, segment := range strings.Split(value, "/") {
		if segment == "" || segment == "." || segment == ".." {
			return errors.New("path must not contain empty, dot, or parent segments")
		}
	}
	return nil
}

func ensureInside(root, target string) error {
	relative, err := filepath.Rel(root, target)
	if err != nil || relative == ".." || strings.HasPrefix(relative, ".."+string(filepath.Separator)) || filepath.IsAbs(relative) {
		return errors.New("path resolves outside repository root")
	}
	return nil
}
