package repository

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"unicode"

	exposurev1 "github.com/opsi-dev/opsi/contracts/go/exposurev1"
	"gopkg.in/yaml.v3"
)

const configComment = "# Generated by opsi init. Review before committing.\n"

var serviceKeyPattern = regexp.MustCompile(`^[a-z0-9](?:[a-z0-9_-]{0,61}[a-z0-9])?$`)
var platformPattern = regexp.MustCompile(`^[a-z0-9][a-z0-9._-]*/[a-z0-9][a-z0-9._-]*(?:/[a-z0-9][a-z0-9._-]*)?$`)
var environmentNamePattern = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]{0,127}$`)

// ConfigOptions is the compatibility input used by opsi init. It renders one
// service in the v2 repository contract.
type ConfigOptions struct {
	ServiceKey string
	Context    string
	Dockerfile string
	Platform   string
	Branch     string
	PreviewPRs bool
}

type ConfigV2 struct {
	Version   int          `json:"version" yaml:"version"`
	Resources []ResourceV2 `json:"resources,omitempty" yaml:"resources,omitempty"`
	Services  []ServiceV2  `json:"services" yaml:"services"`
}

type ServiceV2 struct {
	Key          string     `json:"key" yaml:"key"`
	Build        BuildV2    `json:"build" yaml:"build"`
	WatchPaths   []string   `json:"watch_paths" yaml:"watchPaths"`
	SharedPaths  []string   `json:"shared_paths" yaml:"sharedPaths"`
	Dependencies []string   `json:"dependencies" yaml:"dependencies"`
	Runtime      *RuntimeV2 `json:"runtime,omitempty" yaml:"runtime,omitempty"`
	Deploy       DeployV2   `json:"deploy" yaml:"deploy"`
}

// ResourceV2 is repository-owned infrastructure intent. It contains no
// credentials and is compiled into the canonical resourcev1 authority only
// after a deployment plan has been reviewed and approved.
type ResourceV2 struct {
	LogicalName string            `json:"logical_name" yaml:"logicalName"`
	Type        string            `json:"type" yaml:"type"`
	Managed     bool              `json:"managed" yaml:"managed"`
	Required    bool              `json:"required" yaml:"required"`
	Persistence *PersistenceV2    `json:"persistence,omitempty" yaml:"persistence,omitempty"`
	Settings    map[string]string `json:"settings,omitempty" yaml:"settings,omitempty"`
}

type PersistenceV2 struct {
	Persistent bool   `json:"persistent" yaml:"persistent"`
	SizeBytes  int64  `json:"size_bytes,omitempty" yaml:"sizeBytes,omitempty"`
	PolicyRef  string `json:"policy_ref,omitempty" yaml:"policyRef,omitempty"`
}

type RuntimeV2 struct {
	Port         int                   `json:"port,omitempty" yaml:"port,omitempty"`
	Environment  map[string]string     `json:"environment,omitempty" yaml:"environment,omitempty"`
	Capacity     *RuntimeCapacityV2    `json:"capacity,omitempty" yaml:"capacity,omitempty"`
	Exposure     *RuntimeExposureV2    `json:"exposure,omitempty" yaml:"exposure,omitempty"`
	Secrets      []RuntimeSecretV2     `json:"secrets,omitempty" yaml:"secrets,omitempty"`
	Bindings     []RuntimeBindingV2    `json:"bindings,omitempty" yaml:"bindings,omitempty"`
	Dependencies []RuntimeDependencyV2 `json:"dependencies,omitempty" yaml:"dependencies,omitempty"`
}

type RuntimeCapacityV2 struct {
	Replicas    int32 `json:"replicas,omitempty" yaml:"replicas,omitempty"`
	CPUMilli    int64 `json:"cpu_milli,omitempty" yaml:"cpuMilli,omitempty"`
	MemoryBytes int64 `json:"memory_bytes,omitempty" yaml:"memoryBytes,omitempty"`
}

type RuntimeExposureV2 struct {
	Mode     string `json:"mode" yaml:"mode"`
	Hostname string `json:"hostname,omitempty" yaml:"hostname,omitempty"`
}

type RuntimeSecretV2 struct {
	LogicalName     string `json:"logical_name" yaml:"logicalName"`
	EnvironmentName string `json:"environment_name" yaml:"environmentName"`
	Source          string `json:"source" yaml:"source"`
	Reference       string `json:"reference,omitempty" yaml:"reference,omitempty"`
}

type RuntimeBindingV2 struct {
	Kind   string `json:"kind" yaml:"kind"`
	Target string `json:"target" yaml:"target"`
	Path   string `json:"path,omitempty" yaml:"path,omitempty"`
}

type RuntimeInjectionV2 struct {
	EnvironmentName string `json:"environment_name" yaml:"environmentName"`
	SymbolicSource  string `json:"symbolic_source" yaml:"symbolicSource"`
}

type RuntimeVerificationV2 struct {
	Type           string `json:"type" yaml:"type"`
	Path           string `json:"path,omitempty" yaml:"path,omitempty"`
	ExpectedStatus int    `json:"expected_status,omitempty" yaml:"expectedStatus,omitempty"`
}

type RuntimeDependencyV2 struct {
	Target       string                 `json:"target" yaml:"target"`
	Protocol     string                 `json:"protocol" yaml:"protocol"`
	Strategy     string                 `json:"strategy,omitempty" yaml:"strategy,omitempty"`
	Path         string                 `json:"path,omitempty" yaml:"path,omitempty"`
	Required     bool                   `json:"required" yaml:"required"`
	Injections   []RuntimeInjectionV2   `json:"injections,omitempty" yaml:"injections,omitempty"`
	Verification *RuntimeVerificationV2 `json:"verification,omitempty" yaml:"verification,omitempty"`
}

type BuildV2 struct {
	Context    string `json:"context" yaml:"context"`
	Dockerfile string `json:"dockerfile" yaml:"dockerfile"`
	Platform   string `json:"platform" yaml:"platform"`
}

type DeployV2 struct {
	Production ProductionV2 `json:"production" yaml:"production"`
	Preview    PreviewV2    `json:"preview" yaml:"preview"`
}

type ProductionV2 struct {
	Enabled  bool     `json:"enabled" yaml:"enabled"`
	Branches []string `json:"branches" yaml:"branches"`
}

type PreviewV2 struct {
	Enabled      bool `json:"enabled" yaml:"enabled"`
	PullRequests bool `json:"pull_requests" yaml:"pullRequests"`
}

func ValidateServiceKey(value string) error {
	if len(value) < 1 || len(value) > 63 || !serviceKeyPattern.MatchString(value) {
		return errors.New("service key must be 1-63 lowercase ASCII characters with alphanumeric ends and only '-', '_' inside")
	}
	return nil
}

func ValidateConfigPath(value string) error   { return validateManagedPath(value, ".opsi") }
func ValidateWorkflowPath(value string) error { return validateManagedPath(value, ".github/workflows") }

func validateManagedPath(value, prefix string) error {
	if err := validateSlashRelativePath(value, false); err != nil {
		return err
	}
	if value == prefix || !strings.HasPrefix(value, prefix+"/") {
		return fmt.Errorf("path must be inside %s/", prefix)
	}
	return nil
}

func ValidateBuildInputs(repoRoot, contextPath, dockerfilePath, platform, branch string) error {
	if err := validatePlatform(platform); err != nil {
		return err
	}
	if err := validateSlashRelativePath(contextPath, true); err != nil {
		return fmt.Errorf("invalid build context: %w", err)
	}
	if err := validateSlashRelativePath(dockerfilePath, false); err != nil {
		return fmt.Errorf("invalid Dockerfile path: %w", err)
	}
	if err := ValidateBranch(branch); err != nil {
		return err
	}
	root, err := filepath.EvalSymlinks(repoRoot)
	if err != nil {
		return fmt.Errorf("resolve repository root: %w", err)
	}
	contextResolved, err := filepath.EvalSymlinks(filepath.Join(root, filepath.FromSlash(contextPath)))
	if err != nil {
		return fmt.Errorf("resolve build context: %w", err)
	}
	if err := ensureInside(root, contextResolved); err != nil {
		return fmt.Errorf("build context: %w", err)
	}
	contextInfo, err := os.Stat(contextResolved)
	if err != nil || !contextInfo.IsDir() {
		return errors.New("build context must be an existing directory")
	}
	dockerfileResolved, err := filepath.EvalSymlinks(filepath.Join(root, filepath.FromSlash(dockerfilePath)))
	if err != nil {
		return fmt.Errorf("resolve Dockerfile: %w", err)
	}
	if err := ensureInside(root, dockerfileResolved); err != nil {
		return fmt.Errorf("Dockerfile: %w", err)
	}
	dockerfileInfo, err := os.Stat(dockerfileResolved)
	if err != nil || !dockerfileInfo.Mode().IsRegular() {
		return errors.New("Dockerfile must be an existing regular file")
	}
	return nil
}

func ValidateBranch(value string) error {
	if value == "" || value == "@" || strings.HasPrefix(value, "-") || strings.HasSuffix(value, ".") || strings.HasSuffix(value, "/") {
		return errors.New("production branch is not a valid Git ref name")
	}
	if strings.Contains(value, "..") || strings.Contains(value, "@{") || strings.Contains(value, "//") || strings.IndexAny(value, " ~^:?*[\\") >= 0 || strings.IndexFunc(value, unicode.IsControl) >= 0 {
		return errors.New("production branch is not a valid Git ref name")
	}
	for _, segment := range strings.Split(value, "/") {
		if segment == "" || strings.HasPrefix(segment, ".") || strings.HasSuffix(segment, ".lock") {
			return errors.New("production branch is not a valid Git ref name")
		}
	}
	return nil
}

func validatePlatform(value string) error {
	if value != "linux/amd64" || !platformPattern.MatchString(value) {
		return errors.New("R5-006 supports only linux/amd64")
	}
	return nil
}

func RenderConfig(options ConfigOptions) ([]byte, error) {
	if err := ValidateServiceKey(options.ServiceKey); err != nil {
		return nil, err
	}
	if err := ValidateBranch(options.Branch); err != nil {
		return nil, err
	}
	return RenderConfigV2(ConfigV2{
		Version: 2,
		Services: []ServiceV2{{
			Key:          options.ServiceKey,
			Build:        BuildV2{Context: options.Context, Dockerfile: options.Dockerfile, Platform: options.Platform},
			WatchPaths:   []string{},
			SharedPaths:  []string{},
			Dependencies: []string{},
			Deploy: DeployV2{
				Production: ProductionV2{Enabled: true, Branches: []string{options.Branch}},
				Preview:    PreviewV2{Enabled: options.PreviewPRs, PullRequests: options.PreviewPRs},
			},
		}},
	})
}

func RenderConfigV2(cfg ConfigV2) ([]byte, error) {
	if err := ValidateConfig("", &cfg); err != nil {
		return nil, err
	}
	cfg = canonicalConfig(cfg)
	var output bytes.Buffer
	encoder := yaml.NewEncoder(&output)
	encoder.SetIndent(2)
	if err := encoder.Encode(cfg); err != nil {
		return nil, fmt.Errorf("render repository config: %w", err)
	}
	if err := encoder.Close(); err != nil {
		return nil, fmt.Errorf("finish repository config: %w", err)
	}
	return append([]byte(configComment), output.Bytes()...), nil
}

func ValidateConfig(repoRoot string, cfg *ConfigV2) error {
	if cfg == nil || cfg.Version != 2 {
		return errors.New("config version must be 2")
	}
	if len(cfg.Services) == 0 || len(cfg.Services) > 128 {
		return errors.New("config must contain 1-128 services")
	}
	seenResources := map[string]bool{}
	for i := range cfg.Resources {
		resource := &cfg.Resources[i]
		if err := ValidateServiceKey(resource.LogicalName); err != nil {
			return fmt.Errorf("resource %q logical name: %w", resource.LogicalName, err)
		}
		if seenResources[resource.LogicalName] {
			return fmt.Errorf("duplicate resource logical name %q", resource.LogicalName)
		}
		seenResources[resource.LogicalName] = true
		switch resource.Type {
		case "postgres", "redis", "nats", "rabbitmq", "kafka":
		default:
			return fmt.Errorf("resource %s has unsupported type %q", resource.LogicalName, resource.Type)
		}
		if resource.Managed && resource.Type == "kafka" {
			return fmt.Errorf("resource %s: managed Kafka is unsupported", resource.LogicalName)
		}
		if resource.Persistence != nil {
			if resource.Persistence.SizeBytes < 0 || (!resource.Persistence.Persistent && (resource.Persistence.SizeBytes != 0 || resource.Persistence.PolicyRef != "")) {
				return fmt.Errorf("resource %s persistence intent is invalid", resource.LogicalName)
			}
		}
		for name, value := range resource.Settings {
			if !environmentNamePattern.MatchString(name) || containsControl(value) || secretLikeName(name) {
				return fmt.Errorf("resource %s setting %q is invalid or secret-bearing", resource.LogicalName, name)
			}
		}
	}
	declaredServices := map[string]bool{}
	for _, service := range cfg.Services {
		if err := ValidateServiceKey(service.Key); err != nil {
			return fmt.Errorf("service %q: %w", service.Key, err)
		}
		if declaredServices[service.Key] {
			return fmt.Errorf("duplicate service key %q", service.Key)
		}
		declaredServices[service.Key] = true
	}
	seen := map[string]bool{}
	for i := range cfg.Services {
		s := &cfg.Services[i]
		if err := ValidateServiceKey(s.Key); err != nil {
			return fmt.Errorf("service %q: %w", s.Key, err)
		}
		if seen[s.Key] {
			return fmt.Errorf("duplicate service key %q", s.Key)
		}
		seen[s.Key] = true
		if err := validatePlatform(s.Build.Platform); err != nil {
			return fmt.Errorf("service %s: %w", s.Key, err)
		}
		if err := validateSlashRelativePath(s.Build.Context, true); err != nil {
			return fmt.Errorf("service %s context: %w", s.Key, err)
		}
		if err := validateSlashRelativePath(s.Build.Dockerfile, false); err != nil {
			return fmt.Errorf("service %s Dockerfile: %w", s.Key, err)
		}
		if len(s.WatchPaths) > 64 || len(s.SharedPaths) > 64 || len(s.Dependencies) > 64 || len(s.Deploy.Production.Branches) > 64 {
			return fmt.Errorf("service %s exceeds a 64-entry list limit", s.Key)
		}
		if duplicate := firstDuplicate(s.WatchPaths); duplicate != "" {
			return fmt.Errorf("service %s has duplicate watch path %q", s.Key, duplicate)
		}
		if duplicate := firstDuplicate(s.SharedPaths); duplicate != "" {
			return fmt.Errorf("service %s has duplicate shared path %q", s.Key, duplicate)
		}
		if duplicate := firstDuplicate(s.Dependencies); duplicate != "" {
			return fmt.Errorf("service %s has duplicate dependency %q", s.Key, duplicate)
		}
		if duplicate := firstDuplicate(s.Deploy.Production.Branches); duplicate != "" {
			return fmt.Errorf("service %s has duplicate production branch %q", s.Key, duplicate)
		}
		for _, p := range append(append([]string{}, s.WatchPaths...), s.SharedPaths...) {
			if err := validateSlashRelativePath(p, true); err != nil {
				return fmt.Errorf("service %s path: %w", s.Key, err)
			}
			if repoRoot != "" {
				if err := validatePathSymlinks(repoRoot, p); err != nil {
					return fmt.Errorf("service %s path %s: %w", s.Key, p, err)
				}
			}
		}
		if repoRoot != "" {
			if err := validatePathSymlinks(repoRoot, s.Build.Context); err != nil {
				return fmt.Errorf("service %s context: %w", s.Key, err)
			}
			if err := validatePathSymlinks(repoRoot, s.Build.Dockerfile); err != nil {
				return fmt.Errorf("service %s Dockerfile: %w", s.Key, err)
			}
		}
		if s.Deploy.Production.Enabled && len(s.Deploy.Production.Branches) == 0 {
			return fmt.Errorf("service %s production intent requires a branch", s.Key)
		}
		if !s.Deploy.Production.Enabled && len(s.Deploy.Production.Branches) > 0 {
			return fmt.Errorf("service %s disabled production intent must not contain branches", s.Key)
		}
		for _, branch := range s.Deploy.Production.Branches {
			if err := ValidateBranch(branch); err != nil {
				return fmt.Errorf("service %s: %w", s.Key, err)
			}
		}
		if s.Deploy.Preview.PullRequests != s.Deploy.Preview.Enabled {
			return fmt.Errorf("service %s preview enabled must match pullRequests intent", s.Key)
		}
		if err := validateRuntimeV2(*s, declaredServices, seenResources); err != nil {
			return err
		}
	}
	for _, s := range cfg.Services {
		for _, dep := range s.Dependencies {
			if dep == s.Key || !seen[dep] {
				return fmt.Errorf("service %s has invalid dependency %q", s.Key, dep)
			}
		}
	}
	if cycle := dependencyCycle(*cfg); cycle != "" {
		return fmt.Errorf("service dependency cycle: %s", cycle)
	}
	if repoRoot != "" {
		if root, err := filepath.EvalSymlinks(repoRoot); err != nil {
			return fmt.Errorf("resolve repository root: %w", err)
		} else if err := ensureInside(root, root); err != nil {
			return err
		}
	}
	return nil
}

func validateRuntimeV2(service ServiceV2, services, resources map[string]bool) error {
	runtime := service.Runtime
	if runtime == nil {
		return nil
	}
	if runtime.Port < 0 || runtime.Port > 65535 {
		return fmt.Errorf("service %s runtime port is invalid", service.Key)
	}
	for name, value := range runtime.Environment {
		if !environmentNamePattern.MatchString(name) || containsControl(value) || secretLikeName(name) {
			return fmt.Errorf("service %s environment %q is invalid or secret-bearing", service.Key, name)
		}
	}
	if runtime.Capacity != nil && (runtime.Capacity.Replicas < 0 || runtime.Capacity.CPUMilli < 0 || runtime.Capacity.MemoryBytes < 0) {
		return fmt.Errorf("service %s runtime capacity is invalid", service.Key)
	}
	if runtime.Exposure != nil {
		switch runtime.Exposure.Mode {
		case "none", "internal":
			if runtime.Exposure.Hostname != "" {
				return fmt.Errorf("service %s non-public exposure must not contain a hostname", service.Key)
			}
		case "public":
			hostname, err := exposurev1.NormalizeHostname(runtime.Exposure.Hostname)
			if err != nil || hostname != runtime.Exposure.Hostname {
				return fmt.Errorf("service %s public exposure hostname is invalid", service.Key)
			}
		default:
			return fmt.Errorf("service %s exposure mode is invalid", service.Key)
		}
	}
	secretNames, secretEnvironments := map[string]bool{}, map[string]bool{}
	for _, secret := range runtime.Secrets {
		if err := ValidateServiceKey(secret.LogicalName); err != nil || !environmentNamePattern.MatchString(secret.EnvironmentName) || secretNames[secret.LogicalName] || secretEnvironments[secret.EnvironmentName] {
			return fmt.Errorf("service %s contains an invalid or duplicate runtime secret", service.Key)
		}
		secretNames[secret.LogicalName], secretEnvironments[secret.EnvironmentName] = true, true
		switch secret.Source {
		case "generated":
			if secret.Reference != "" {
				return fmt.Errorf("service %s generated secret %s must not contain a reference", service.Key, secret.LogicalName)
			}
		case "external":
			if containsControl(secret.Reference) {
				return fmt.Errorf("service %s external secret %s reference is invalid", service.Key, secret.LogicalName)
			}
		default:
			return fmt.Errorf("service %s secret %s source must be generated or external", service.Key, secret.LogicalName)
		}
	}
	bindings := map[string]bool{}
	for _, binding := range runtime.Bindings {
		if (binding.Kind != "internal_http" && binding.Kind != "browser_http") || !services[binding.Target] || binding.Target == service.Key {
			return fmt.Errorf("service %s contains an invalid runtime binding", service.Key)
		}
		if binding.Kind == "browser_http" && binding.Path == "" {
			return fmt.Errorf("service %s browser binding requires a same-origin path", service.Key)
		}
		if binding.Path != "" {
			normalized, err := exposurev1.NormalizePath(binding.Path)
			if err != nil || normalized != binding.Path {
				return fmt.Errorf("service %s binding path is invalid", service.Key)
			}
		}
		key := binding.Kind + "\x00" + binding.Target + "\x00" + binding.Path
		if bindings[key] {
			return fmt.Errorf("service %s contains duplicate runtime binding %q", service.Key, binding.Target)
		}
		bindings[key] = true
	}
	dependencies := map[string]bool{}
	for _, dependency := range runtime.Dependencies {
		if (!services[dependency.Target] && !resources[dependency.Target]) || dependency.Target == service.Key || dependency.Protocol == "" {
			return fmt.Errorf("service %s contains an invalid runtime dependency target", service.Key)
		}
		switch dependency.Protocol {
		case "http", "postgres", "redis", "nats", "amqp", "tcp", "custom":
		default:
			return fmt.Errorf("service %s dependency %s protocol is unsupported", service.Key, dependency.Target)
		}
		if dependency.Path != "" {
			normalized, err := exposurev1.NormalizePath(dependency.Path)
			if err != nil || normalized != dependency.Path {
				return fmt.Errorf("service %s dependency %s path is invalid", service.Key, dependency.Target)
			}
		}
		key := dependency.Target + "\x00" + dependency.Protocol + "\x00" + dependency.Strategy + "\x00" + dependency.Path
		if dependencies[key] {
			return fmt.Errorf("service %s contains duplicate runtime dependency %s", service.Key, dependency.Target)
		}
		dependencies[key] = true
		mappings := map[string]bool{}
		for _, injection := range dependency.Injections {
			if !environmentNamePattern.MatchString(injection.EnvironmentName) || injection.SymbolicSource == "" || containsControl(injection.SymbolicSource) || mappings[injection.EnvironmentName] {
				return fmt.Errorf("service %s dependency %s contains an invalid injection", service.Key, dependency.Target)
			}
			mappings[injection.EnvironmentName] = true
		}
		if dependency.Verification != nil {
			verification := dependency.Verification
			if verification.Type != "consumer_http" || verification.Path == "" || verification.ExpectedStatus < 100 || verification.ExpectedStatus > 599 {
				return fmt.Errorf("service %s dependency %s verification contract is invalid", service.Key, dependency.Target)
			}
			normalized, err := exposurev1.NormalizePath(verification.Path)
			if err != nil || normalized != verification.Path {
				return fmt.Errorf("service %s dependency %s verification path is invalid", service.Key, dependency.Target)
			}
		}
	}
	return nil
}

func containsControl(value string) bool { return strings.IndexFunc(value, unicode.IsControl) >= 0 }

func secretLikeName(value string) bool {
	name := strings.ToLower(strings.ReplaceAll(value, "_", ""))
	for _, marker := range []string{"password", "passwd", "secret", "token", "privatekey", "signingkey", "apikey", "connectionstring"} {
		if strings.Contains(name, marker) {
			return true
		}
	}
	return false
}

func validatePathSymlinks(root, relative string) error {
	resolvedRoot, err := filepath.EvalSymlinks(root)
	if err != nil {
		return err
	}
	current := resolvedRoot
	for _, segment := range strings.Split(relative, "/") {
		if segment == "." {
			continue
		}
		current = filepath.Join(current, segment)
		info, statErr := os.Lstat(current)
		if errors.Is(statErr, os.ErrNotExist) {
			break
		}
		if statErr != nil {
			return statErr
		}
		if info.Mode()&os.ModeSymlink != 0 {
			target, err := filepath.EvalSymlinks(current)
			if err != nil {
				return err
			}
			if err := ensureInside(resolvedRoot, target); err != nil {
				return err
			}
		}
	}
	return nil
}

func canonicalConfig(cfg ConfigV2) ConfigV2 {
	cfg.Version = 2
	sort.Slice(cfg.Resources, func(i, j int) bool { return cfg.Resources[i].LogicalName < cfg.Resources[j].LogicalName })
	sort.Slice(cfg.Services, func(i, j int) bool { return cfg.Services[i].Key < cfg.Services[j].Key })
	for i := range cfg.Services {
		s := &cfg.Services[i]
		s.WatchPaths = uniqueSorted(s.WatchPaths)
		s.SharedPaths = uniqueSorted(s.SharedPaths)
		s.Dependencies = uniqueSorted(s.Dependencies)
		s.Deploy.Production.Branches = uniqueSorted(s.Deploy.Production.Branches)
		if s.WatchPaths == nil {
			s.WatchPaths = []string{}
		}
		if s.SharedPaths == nil {
			s.SharedPaths = []string{}
		}
		if s.Dependencies == nil {
			s.Dependencies = []string{}
		}
		if s.Deploy.Production.Branches == nil {
			s.Deploy.Production.Branches = []string{}
		}
		if s.Runtime != nil {
			runtime := s.Runtime
			sort.Slice(runtime.Secrets, func(i, j int) bool { return runtime.Secrets[i].LogicalName < runtime.Secrets[j].LogicalName })
			sort.Slice(runtime.Bindings, func(i, j int) bool {
				left, right := runtime.Bindings[i], runtime.Bindings[j]
				return left.Kind+"\x00"+left.Target+"\x00"+left.Path < right.Kind+"\x00"+right.Target+"\x00"+right.Path
			})
			for j := range runtime.Dependencies {
				sort.Slice(runtime.Dependencies[j].Injections, func(k, l int) bool {
					return runtime.Dependencies[j].Injections[k].EnvironmentName < runtime.Dependencies[j].Injections[l].EnvironmentName
				})
			}
			sort.Slice(runtime.Dependencies, func(i, j int) bool {
				left, right := runtime.Dependencies[i], runtime.Dependencies[j]
				return left.Target+"\x00"+left.Protocol+"\x00"+left.Strategy+"\x00"+left.Path < right.Target+"\x00"+right.Protocol+"\x00"+right.Strategy+"\x00"+right.Path
			})
		}
	}
	return cfg
}

func uniqueSorted(values []string) []string {
	out := append([]string(nil), values...)
	sort.Strings(out)
	result := out[:0]
	for _, v := range out {
		if len(result) == 0 || result[len(result)-1] != v {
			result = append(result, v)
		}
	}
	return result
}

func firstDuplicate(values []string) string {
	seen := map[string]bool{}
	for _, value := range values {
		if seen[value] {
			return value
		}
		seen[value] = true
	}
	return ""
}

func dependencyCycle(cfg ConfigV2) string {
	state := map[string]int{}
	stack := []string{}
	var visit func(string) string
	visit = func(key string) string {
		state[key] = 1
		stack = append(stack, key)
		var svc ServiceV2
		for _, candidate := range cfg.Services {
			if candidate.Key == key {
				svc = candidate
				break
			}
		}
		for _, dep := range svc.Dependencies {
			if state[dep] == 1 {
				return dep
			}
			if state[dep] == 0 {
				if cycle := visit(dep); cycle != "" {
					return cycle
				}
			}
		}
		stack = stack[:len(stack)-1]
		state[key] = 2
		return ""
	}
	for _, svc := range cfg.Services {
		if state[svc.Key] == 0 {
			if cycle := visit(svc.Key); cycle != "" {
				return cycle
			}
		}
	}
	return ""
}

func UpsertService(cfg ConfigV2, service ServiceV2) (ConfigV2, error) {
	if err := ValidateServiceKey(service.Key); err != nil {
		return ConfigV2{}, err
	}
	found := false
	for i := range cfg.Services {
		if cfg.Services[i].Key == service.Key {
			// CLI add/update commands do not own runtime intent. Preserve the
			// repository-declared runtime contract unless the caller explicitly
			// supplied a replacement.
			if service.Runtime == nil {
				service.Runtime = cfg.Services[i].Runtime
			}
			cfg.Services[i] = service
			found = true
			break
		}
	}
	if !found {
		cfg.Services = append(cfg.Services, service)
	}
	if err := ValidateConfig("", &cfg); err != nil {
		return ConfigV2{}, err
	}
	return canonicalConfig(cfg), nil
}

func ConfigHash(data []byte) string { sum := sha256.Sum256(data); return hex.EncodeToString(sum[:]) }

func (s ServiceV2) Paths() []string {
	return append(append([]string{s.Build.Context, s.Build.Dockerfile}, s.WatchPaths...), s.SharedPaths...)
}

func validateSlashRelativePath(value string, allowDot bool) error {
	if value == "" || len(value) > 512 || strings.Contains(value, "\\") || strings.IndexFunc(value, unicode.IsControl) >= 0 || path.IsAbs(value) || filepath.IsAbs(value) {
		return errors.New("path must be a 1-512 byte slash-separated relative path")
	}
	if allowDot && value == "." {
		return nil
	}
	if path.Clean(value) != value {
		return errors.New("path must not contain empty, dot, or parent segments")
	}
	for _, segment := range strings.Split(value, "/") {
		if segment == "" || segment == "." || segment == ".." {
			return errors.New("path must not contain empty, dot, or parent segments")
		}
	}
	return nil
}

func ensureInside(root, target string) error {
	relative, err := filepath.Rel(root, target)
	if err != nil || relative == ".." || strings.HasPrefix(relative, ".."+string(filepath.Separator)) || filepath.IsAbs(relative) {
		return errors.New("path resolves outside repository root")
	}
	return nil
}
