package repository

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"strings"
	"unicode"

	"gopkg.in/yaml.v3"
)

const configComment = "# Generated by opsi init. Review before committing.\n"

var serviceKeyPattern = regexp.MustCompile(`^[a-z0-9](?:[a-z0-9_-]{0,61}[a-z0-9])?$`)

type ConfigOptions struct {
	ServiceKey string
	Context    string
	Dockerfile string
	Platform   string
	Branch     string
	PreviewPRs bool
}

type ServiceBuildConfig struct {
	APIVersion string           `yaml:"apiVersion"`
	Kind       string           `yaml:"kind"`
	Metadata   ConfigMetadata   `yaml:"metadata"`
	Build      BuildConfig      `yaml:"build"`
	Deploy     DeploymentConfig `yaml:"deploy"`
}

type ConfigMetadata struct {
	ServiceKey string `yaml:"serviceKey"`
}

type BuildConfig struct {
	Context    string   `yaml:"context"`
	Dockerfile string   `yaml:"dockerfile"`
	Platforms  []string `yaml:"platforms"`
}

type DeploymentConfig struct {
	Production ProductionConfig `yaml:"production"`
	Preview    PreviewConfig    `yaml:"preview"`
}

type ProductionConfig struct {
	Branches []string `yaml:"branches"`
}

type PreviewConfig struct {
	PullRequests bool `yaml:"pullRequests"`
}

func ValidateServiceKey(value string) error {
	if len(value) < 1 || len(value) > 63 || !serviceKeyPattern.MatchString(value) {
		return errors.New("service key must be 1-63 lowercase ASCII characters with alphanumeric ends and only '-', '_' inside")
	}
	return nil
}

func ValidateConfigPath(value string) error {
	return validateManagedPath(value, ".opsi")
}

func ValidateWorkflowPath(value string) error {
	return validateManagedPath(value, ".github/workflows")
}

func validateManagedPath(value, prefix string) error {
	if err := validateSlashRelativePath(value, false); err != nil {
		return err
	}
	if value == prefix || !strings.HasPrefix(value, prefix+"/") {
		return fmt.Errorf("path must be inside %s/", prefix)
	}
	return nil
}

func ValidateBuildInputs(repoRoot, contextPath, dockerfilePath, platform, branch string) error {
	if platform != "linux/amd64" {
		return errors.New("P10 supports only linux/amd64")
	}
	if err := validateSlashRelativePath(contextPath, true); err != nil {
		return fmt.Errorf("invalid build context: %w", err)
	}
	if err := validateSlashRelativePath(dockerfilePath, false); err != nil {
		return fmt.Errorf("invalid Dockerfile path: %w", err)
	}
	if err := ValidateBranch(branch); err != nil {
		return err
	}
	root, err := filepath.EvalSymlinks(repoRoot)
	if err != nil {
		return fmt.Errorf("resolve repository root: %w", err)
	}
	contextResolved, err := filepath.EvalSymlinks(filepath.Join(root, filepath.FromSlash(contextPath)))
	if err != nil {
		return fmt.Errorf("resolve build context: %w", err)
	}
	if err := ensureInside(root, contextResolved); err != nil {
		return fmt.Errorf("build context: %w", err)
	}
	contextInfo, err := os.Stat(contextResolved)
	if err != nil || !contextInfo.IsDir() {
		return errors.New("build context must be an existing directory")
	}
	dockerfileResolved, err := filepath.EvalSymlinks(filepath.Join(root, filepath.FromSlash(dockerfilePath)))
	if err != nil {
		return fmt.Errorf("resolve Dockerfile: %w", err)
	}
	if err := ensureInside(root, dockerfileResolved); err != nil {
		return fmt.Errorf("Dockerfile: %w", err)
	}
	dockerfileInfo, err := os.Stat(dockerfileResolved)
	if err != nil || !dockerfileInfo.Mode().IsRegular() {
		return errors.New("Dockerfile must be an existing regular file")
	}
	return nil
}

func ValidateBranch(value string) error {
	if value == "" || value == "@" || strings.HasPrefix(value, "-") || strings.HasSuffix(value, ".") || strings.HasSuffix(value, "/") {
		return errors.New("production branch is not a valid Git ref name")
	}
	if strings.Contains(value, "..") || strings.Contains(value, "@{") || strings.Contains(value, "//") || strings.IndexAny(value, " ~^:?*[\\") >= 0 || strings.IndexFunc(value, unicode.IsControl) >= 0 {
		return errors.New("production branch is not a valid Git ref name")
	}
	for _, segment := range strings.Split(value, "/") {
		if segment == "" || strings.HasPrefix(segment, ".") || strings.HasSuffix(segment, ".lock") {
			return errors.New("production branch is not a valid Git ref name")
		}
	}
	return nil
}

func RenderConfig(options ConfigOptions) ([]byte, error) {
	if err := ValidateServiceKey(options.ServiceKey); err != nil {
		return nil, err
	}
	config := ServiceBuildConfig{
		APIVersion: "cd.opsi.dev/v1alpha1",
		Kind:       "ServiceBuild",
		Metadata:   ConfigMetadata{ServiceKey: options.ServiceKey},
		Build: BuildConfig{
			Context:    options.Context,
			Dockerfile: options.Dockerfile,
			Platforms:  []string{options.Platform},
		},
		Deploy: DeploymentConfig{
			Production: ProductionConfig{Branches: []string{options.Branch}},
			Preview:    PreviewConfig{PullRequests: options.PreviewPRs},
		},
	}
	var output bytes.Buffer
	encoder := yaml.NewEncoder(&output)
	encoder.SetIndent(2)
	err := encoder.Encode(config)
	if err != nil {
		return nil, fmt.Errorf("render repository config: %w", err)
	}
	if err := encoder.Close(); err != nil {
		return nil, fmt.Errorf("finish repository config: %w", err)
	}
	return append([]byte(configComment), output.Bytes()...), nil
}

func validateSlashRelativePath(value string, allowDot bool) error {
	if value == "" || strings.Contains(value, "\\") || strings.IndexFunc(value, unicode.IsControl) >= 0 || path.IsAbs(value) || filepath.IsAbs(value) {
		return errors.New("path must be a non-empty slash-separated relative path")
	}
	if allowDot && value == "." {
		return nil
	}
	if path.Clean(value) != value {
		return errors.New("path must not contain empty, dot, or parent segments")
	}
	for _, segment := range strings.Split(value, "/") {
		if segment == "" || segment == "." || segment == ".." {
			return errors.New("path must not contain empty, dot, or parent segments")
		}
	}
	return nil
}

func ensureInside(root, target string) error {
	relative, err := filepath.Rel(root, target)
	if err != nil || relative == ".." || strings.HasPrefix(relative, ".."+string(filepath.Separator)) || filepath.IsAbs(relative) {
		return errors.New("path resolves outside repository root")
	}
	return nil
}
