package repository

const workflow = `# Generated by opsi init. Requires an immutable Opsi CLI release on PATH.
name: Opsi CD

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: opsi-cd-${{ github.repository_id }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  plan:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
      has-services: ${{ steps.matrix.outputs.has-services }}
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Resolve affected services
        env:
          OPSI_BASE: ${{ github.event.pull_request.base.sha || github.event.before || '' }}
          OPSI_EVENT: ${{ github.event_name == 'pull_request' && 'pull_request' || (github.event_name == 'push' && 'push' || 'initial') }}
          OPSI_HEAD: ${{ github.event.pull_request.head.sha || github.sha }}
        run: opsi cd plan --event "$OPSI_EVENT" --base "$OPSI_BASE" --head "$OPSI_HEAD" --json > "$RUNNER_TEMP/opsi-plan.json"
        shell: bash
      - name: Create bounded matrix
        id: matrix
        env:
          OPSI_PLAN: ${{ runner.temp }}/opsi-plan.json
        run: |
          python3 - "$OPSI_PLAN" "$GITHUB_OUTPUT" <<'PY'
          import json
          import pathlib
          import sys

          plan = json.loads(pathlib.Path(sys.argv[1]).read_text(encoding="utf-8"))
          matrix = plan.get("matrix", [])
          if not isinstance(matrix, list) or len(matrix) > 128:
              raise SystemExit("invalid or oversized Opsi matrix")
          compact = json.dumps({"service": matrix}, separators=(",", ":"), sort_keys=True)
          with pathlib.Path(sys.argv[2]).open("a", encoding="utf-8") as output:
              output.write("matrix=" + compact + "\n")
              output.write("has-services=" + ("true" if matrix else "false") + "\n")
          PY
        shell: bash

  build:
    needs: plan
    if: needs.plan.outputs.has-services == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix: ${{ fromJSON(needs.plan.outputs.matrix) }}
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: Build affected service without publishing
        env:
          OPSI_BUILD_CONTEXT: ${{ matrix.service.context }}
          OPSI_DOCKERFILE: ${{ matrix.service.dockerfile }}
          OPSI_PLATFORM: ${{ matrix.service.platform }}
        run: docker build --platform "$OPSI_PLATFORM" --file "$OPSI_DOCKERFILE" "$OPSI_BUILD_CONTEXT"
        shell: bash
`

func RenderWorkflow(_ ...ConfigV2) []byte { return []byte(workflow) }
