package repository

const workflow = `# Generated by opsi init. P11/P13 will activate trusted build delivery.
name: Opsi CD Bootstrap

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  bootstrap:
    runs-on: ubuntu-latest
    steps:
      - name: Opsi bootstrap status
        shell: bash
        run: |
          echo "Opsi repository bootstrap is installed."
          echo "Trusted OIDC build submission is not enabled yet."
`

func RenderWorkflow() []byte {
	return []byte(workflow)
}
