import { Button, Input, Select } from "@/components/ui/primitives";
import { publicSubdomainSuffix, validatePublicSubdomain } from "@/features/deploy/public-subdomain";
import type { GitHubInstallation, GitHubRepository } from "@/lib/contracts/registry";

export function SourceStep({ busy, canMutate, hostname, installationID, installations, linkedInstallationIDs, onConnectInstallation, onDiscover, onHostname, onInstallation, onRepository, onStart, onRef, quotaBlocked, refName, repositories, repositoryID }: { busy: string; canMutate: boolean; hostname: string; installationID: number; installations: GitHubInstallation[]; linkedInstallationIDs: number[]; onConnectInstallation: () => void; onDiscover: () => void; onHostname: (value: string) => void; onInstallation: (value: number) => void; onRepository: (value: number) => void; onStart: () => void; onRef: (value: string) => void; quotaBlocked: boolean; refName: string; repositories: GitHubRepository[]; repositoryID: number }) {
  const selected = repositories.find((item) => item.repository_id === repositoryID);
  const selectedInstallation = installations.find((item) => item.installation_id === installationID);
  const installationNeedsConnection = Boolean(selectedInstallation && !linkedInstallationIDs.includes(selectedInstallation.installation_id));
  const usableRepositories = repositories.filter((item) => item.status === "active" && !item.archived && !item.disabled);
  const repositoryConflict = selected?.claim_status === "conflict";
  const hostnameError = validatePublicSubdomain(hostname);
  const actionLabel = selected?.claim_status === "available" ? "Claim & analyze repository" : busy === "create" ? "Analyzing repository…" : "Analyze repository";
  return (
    <section aria-labelledby="source-step-title" className="mx-auto max-w-2xl border border-outline-variant/30 bg-surface-container p-5 sm:p-7">
      <p className="text-xs font-medium uppercase tracking-wider text-secondary">Source</p>
      <h2 className="mt-2 text-2xl font-semibold" id="source-step-title">Choose a repository to deploy</h2>
      <p className="mt-2 text-sm text-on-surface-variant">Opsi reads one exact commit through your GitHub App installation. It does not write source, create a PR, or require repository workflows.</p>
      <div className="mt-6 space-y-4">
        {installations.length === 0 ? <div className="border border-outline-variant/30 bg-surface-container-low p-4"><p className="text-sm text-on-surface-variant">Authorize GitHub to discover installations available to your account.</p><Button className="mt-3" disabled={Boolean(busy) || !canMutate} onClick={onDiscover} type="button">Continue with GitHub</Button></div> : installationNeedsConnection ? <div className="border border-outline-variant/30 bg-surface-container-low p-4"><label className="block text-sm font-medium" htmlFor="source-installation">GitHub installation</label><Select className="mt-2" disabled={Boolean(busy) || !canMutate} id="source-installation" onChange={(event) => onInstallation(Number(event.target.value))} value={installationID}>{installations.map((installation) => <option key={installation.installation_id} value={installation.installation_id}>{installation.account_login || `Installation ${installation.installation_id}`}</option>)}</Select><Button className="mt-3" disabled={Boolean(busy) || !canMutate} onClick={onDiscover} type="button" variant="outline">Discover again</Button><Button className="ml-2 mt-3" disabled={Boolean(busy) || !canMutate} onClick={onConnectInstallation} type="button">Connect installation</Button></div> : null}
        <label className="block text-sm font-medium" htmlFor="source-repository">Repository</label>
        <Select disabled={Boolean(busy) || !canMutate || installationNeedsConnection} id="source-repository" onChange={(event) => { const id = Number(event.target.value); onRepository(id); const repository = repositories.find((item) => item.repository_id === id); if (repository) onRef(repository.default_branch || "main"); }} value={repositoryID || ""}><option value="">Select a repository</option>{usableRepositories.map((repository) => <option disabled={repository.claim_status === "conflict"} key={repository.repository_id} value={repository.repository_id}>{repository.full_name}{repository.claim_status === "available" ? " · claim required" : repository.claim_status === "conflict" ? " · claimed by another project" : ""}</option>)}</Select>
        <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium" htmlFor="source-ref">Branch or ref<Input disabled={Boolean(busy) || !canMutate} id="source-ref" onChange={(event) => onRef(event.target.value)} value={refName} /></label><label className="text-sm font-medium" htmlFor="source-hostname">Public subdomain<div className="mt-1 flex items-center"><Input aria-describedby="source-hostname-help" aria-invalid={Boolean(hostnameError)} className="rounded-r-none" disabled={Boolean(busy) || !canMutate} id="source-hostname" onChange={(event) => onHostname(event.target.value)} placeholder="tcip" value={hostname} /><span className="min-h-10 border border-l-0 border-outline-variant/40 bg-surface-container-low px-3 py-2 font-mono text-xs text-on-surface-variant">.{publicSubdomainSuffix}</span></div><span className="mt-1 block text-xs font-normal text-on-surface-variant" id="source-hostname-help">Published publicly over HTTPS through Cloudflare.</span></label></div>
      </div>
      {hostnameError && <p className="mt-4 text-sm text-error" role="alert">{hostnameError}</p>}
      {quotaBlocked && <p className="mt-4 text-sm text-error" role="alert">Release an unused public hostname before creating a deployment with a new label.</p>}
      {repositoryConflict && <p className="mt-5 border border-status-warning/40 bg-status-warning/10 p-3 text-sm" role="alert">This repository is claimed by another project. Release it from the owning project or select another repository.</p>}
      {installations.length > 0 && usableRepositories.length === 0 && !installationNeedsConnection && <p className="mt-5 border border-status-warning/40 bg-status-warning/10 p-3 text-sm">The connected installation has no deployable repository. Check its GitHub repository access, then discover again.</p>}
      <div className="mt-7 flex justify-end"><Button disabled={Boolean(busy) || !canMutate || !selected || !refName.trim() || Boolean(hostnameError) || quotaBlocked || installationNeedsConnection || repositoryConflict} onClick={onStart} size="lg"><span>{actionLabel}</span></Button></div>
    </section>
  );
}
