"use client";

import { useEffect, useRef, useState } from "react";
import { Button, Icon } from "@/components/ui/primitives";
import type { ConsoleController } from "@/features/console/types";

export function BootstrapDialog({ console, onClose, onCreated }: { console: ConsoleController; onClose: () => void; onCreated: () => Promise<void> }) {
  const dialog = useRef<HTMLDialogElement>(null);
  const [method, setMethod] = useState("command");
  useEffect(() => { const element = dialog.current; element?.showModal(); return () => { if (element?.open) element.close(); }; }, []);
  return <dialog aria-describedby="bootstrap-description" aria-labelledby="bootstrap-title" className="fixed inset-0 z-50 m-auto flex max-h-[90vh] w-full max-w-xl flex-col gap-5 overflow-y-auto rounded-2xl border border-outline-variant/30 bg-surface-container-low p-6 text-on-surface shadow-2xl backdrop:bg-background/80 backdrop:backdrop-blur-sm" onCancel={(event) => { event.preventDefault(); onClose(); }} ref={dialog}>
    <div className="flex items-start justify-between border-b border-outline-variant/20 pb-4"><div><span className="mb-1 block text-xs font-bold uppercase tracking-wider text-primary">Deploy · Target</span><h2 className="text-xl font-bold" id="bootstrap-title">Connect Server</h2><p className="mt-1 text-xs text-on-surface-variant" id="bootstrap-description">Generate a one-time command, run it on the VPS, then follow progress until Ready.</p></div><button aria-label="Close connect server dialog" autoFocus className="flex min-h-10 min-w-10 items-center justify-center rounded-lg p-2 text-on-surface-variant hover:bg-surface-container-highest hover:text-on-surface" onClick={onClose} type="button"><Icon className="text-[20px]" name="close" /></button></div>
    <ol aria-label="Connect Server steps" className="grid grid-cols-3 gap-2 rounded-xl border border-outline-variant/15 bg-surface-container p-3 text-xs"><li className="font-bold text-primary">1 · Generate</li><li className="text-on-surface-variant">2 · Run on VPS</li><li className="text-on-surface-variant">3 · Wait for Ready</li></ol>
    <form className="space-y-4" onSubmit={(event) => { void console.actions.addServer(event, onCreated); onClose(); }}><label className="grid gap-1.5 text-xs text-on-surface-variant">Role<select aria-label="Role" className="field min-h-10" defaultValue="first_server" name="role" required><option value="first_server">First server</option><option value="worker">Worker</option></select></label><label className="grid gap-1.5 text-xs text-on-surface-variant">Server IP or hostname<input aria-label="Server IP or hostname" autoComplete="off" className="field min-h-10" name="public_host" placeholder="203.0.113.10" required spellCheck={false} /></label>
      <fieldset className="space-y-3 rounded-xl border border-outline-variant/15 bg-surface-container/60 p-4"><legend className="px-1 text-xs font-bold uppercase tracking-wider">Bootstrap method</legend><label className="flex items-start gap-3 rounded-xl border border-outline-variant/20 bg-surface-container-high p-3"><input aria-label="Run bootstrap command" checked={method === "command"} className="mt-1" name="auth_method" onChange={() => setMethod("command")} type="radio" value="command" /><span><strong className="block text-xs">Run bootstrap command</strong><small className="text-on-surface-variant">Recommended. Scoped one-time execution.</small></span></label><details className="text-xs text-on-surface-variant"><summary className="flex min-h-10 cursor-pointer items-center font-medium">Advanced: Bootstrap over SSH</summary><div className="space-y-3 pt-2">{[["password", "SSH Password"], ["private_key", "SSH Private Key"]].map(([value, label]) => <label className="flex items-start gap-3 rounded-xl border border-outline-variant/20 bg-surface-container-high p-3" key={value}><input aria-label={label} checked={method === value} className="mt-1" name="auth_method" onChange={() => setMethod(value)} type="radio" value={value} /><span>{label}</span></label>)}{method !== "command" && <div className="grid grid-cols-2 gap-3"><label>SSH port<input aria-label="SSH port" className="field" defaultValue="22" max="65535" min="1" name="ssh_port" required type="number" /></label><label>SSH username<input aria-label="SSH username" autoComplete="username" className="field" defaultValue="root" name="ssh_username" required /></label></div>}</div></details></fieldset>
      <p className="rounded-xl border border-outline-variant/10 bg-surface-container/40 p-3 text-xs text-on-surface-variant">The issued token expires and is scoped to this reviewed session.</p><div className="flex justify-end gap-3 border-t border-outline-variant/20 pt-3"><Button onClick={onClose} type="button" variant="outline">Cancel</Button><Button type="submit" variant="primary">Generate bootstrap command</Button></div></form>
  </dialog>;
}

export function BootstrapCommand({ command }: { command: string }) {
  const [copyState, setCopyState] = useState("Copy command");
  async function copy() { try { await navigator.clipboard.writeText(command); setCopyState("Copied"); } catch { setCopyState("Copy failed"); } }
  return <section aria-labelledby="bootstrap-command-title" className="bootstrapCommand"><div><div><p className="eyebrow">One-time scoped command</p><h4 id="bootstrap-command-title">Copy, then run on the VPS as root</h4></div><button className="primary" onClick={() => void copy()} type="button">{copyState}</button></div><code>{command}</code><p role="status">Waiting for server. Refresh restores lifecycle facts, not this one-time command.</p></section>;
}
