import { Empty, StatusBadge, Surface } from "@/components/ui/primitives";
import type { ConsoleController } from "@/features/console/types";
import { overallHealth, type SourceState } from "@/features/observability/data";
import type { ObservabilityModel } from "@/features/observability/observability-view";
import { SourceBadge, formatObserved } from "@/features/observability/shared";

export function HealthTab({ console, model }: { console: ConsoleController; model: ObservabilityModel }) {
  const agentAvailable = console.session?.agent_connected === "ok";
  const health = overallHealth(model.data, console.state.services.length, agentAvailable);
  const support = console.state.support;
  const serviceIDs = new Set(console.state.services.map((service) => service.id));
  const unresolvedTelemetry = model.data.telemetry.filter((item) => !serviceIDs.has(item.service_id));
  return <div className="observabilityStack">
    <div className="observabilityHero"><div><p className="eyebrow">Observability starting point</p><h2>Health</h2><p>Factual telemetry, coverage, and next steps.</p></div><div className="heroStatus"><StatusBadge value={health} /><button disabled={model.data.sources.telemetry === "loading"} onClick={() => void model.load()} type="button">Refresh health</button></div></div>
    {model.data.error ? <p className="inlineError" role="alert">{model.data.error}</p> : null}
    <section className="coverageGrid" aria-label="Source coverage"><SourceBadge label="Cloud registry" state={model.data.sources.registry} /><SourceBadge label="Agent telemetry" state={model.data.sources.telemetry} /><SourceBadge label="Incident store" state={model.data.sources.incidents} /><SourceBadge label="Support projection" state={support ? "ready" : "unavailable"} /><div className="coverageItem"><span>Last factual update</span><b>{formatObserved(model.data.summary?.end_unix)}</b></div></section>
    <Surface title="Service health matrix"><div className="healthMatrix"><div className="healthHeader"><span>Service</span><span>Ready / desired</span><span>Restarts</span><span>Errors</span><span>Last seen</span><span>Health</span></div>{console.state.services.length ? console.state.services.map((service) => { const telemetry = model.data.telemetry.find((item) => item.service_id === service.id); const desired = telemetry?.pod_count ?? service.replicas; const ready = telemetry?.ready_pods; const unavailable = !agentAvailable || model.data.sources.telemetry === "unavailable"; const serviceHealth = unavailable ? "unavailable" : telemetry ? ready !== undefined && desired !== undefined && ready < desired ? "degraded" : telemetry.health : "unknown"; return <button className="healthRow" key={service.id} onClick={() => console.navigate({ service: service.id, tab: "metrics" })} type="button"><strong>{service.name}</strong><span data-label="Ready / desired">{unavailable ? "Unavailable" : `${ready ?? "Unknown"}/${desired ?? "Unknown"}`}</span><span data-label="Restarts">{unavailable ? "Unavailable" : telemetry?.restart_count ?? "Unknown"}</span><span data-label="Errors">{unavailable ? "Unavailable" : telemetry?.recent_error_count ?? "Unknown"}</span><span data-label="Last seen">{unavailable ? "Unavailable" : formatObserved(telemetry?.last_seen_unix)}</span><StatusBadge value={serviceHealth} /></button>; }) : <Empty text="No services in this project." />}{unresolvedTelemetry.map((telemetry) => <div className="healthRow" key={`unresolved-${telemetry.service_id}`}><strong>Unresolved identity</strong><span data-label="Ready / desired">{telemetry.ready_pods}/{telemetry.pod_count}</span><span data-label="Restarts">{telemetry.restart_count ?? "Unknown"}</span><span data-label="Errors">{telemetry.recent_error_count ?? "Unknown"}</span><span data-label="Last seen">{formatObserved(telemetry.last_seen_unix)}</span><StatusBadge value="unknown" /></div>)}</div></Surface>
    <div className="observabilityColumns"><Surface title="Active alerts / attention">{support?.active_alerts?.length ? <ul className="compactList">{support.active_alerts.map((alert) => <li key={alert.id}><StatusBadge value={alert.severity} /><b>{alert.title}</b><small>{alert.resource_id || alert.runbook_id}</small></li>)}</ul> : <Empty text={support ? "No active alerts reported." : "Alert source unavailable."} />}</Surface><Surface title="Recent incidents">{model.data.incidents.filter((item) => item.status !== "resolved").length ? <ul className="compactList">{model.data.incidents.filter((item) => item.status !== "resolved").slice(0, 5).map((incident) => <li key={incident.incident_id}><button onClick={() => console.navigate({ tab: "incidents", incident: incident.incident_id })} type="button"><StatusBadge value={incident.severity || "warning"} /><b>{incident.incident_id}</b><small>{incident.service_id || incident.anomaly_type || "Impact not reported"}</small></button></li>)}</ul> : <Empty text={model.data.sources.incidents === "unavailable" ? "Incident source unavailable." : "No open incidents."} />}</Surface></div>
    {support ? <OperationalEvidence support={support} sourceStates={model.data.sources} /> : <details className="evidenceDisclosure"><summary>Operational evidence</summary><p>Support projection unavailable. SLO signals, gates, break-glass policy, request IDs, and runbooks cannot be claimed.</p></details>}
  </div>;
}

function OperationalEvidence({ support, sourceStates }: { support: NonNullable<ConsoleController["state"]["support"]>; sourceStates: Record<string, SourceState> }) {
  return <details className="evidenceDisclosure"><summary>Operational evidence</summary><div className="observabilityColumns"><section><h3>SLO signals</h3>{support.signals.length ? <ul className="compactList">{support.signals.map((signal) => <li key={signal.name}><b>{signal.name}</b><span>{signal.status} · {signal.value} / {signal.target}</span></li>)}</ul> : <p className="muted">Not reported.</p>}</section><section><h3>Production gates & break-glass</h3><ul className="compactList">{support.production_gates.map((gate) => <li key={gate.name}><StatusBadge value={gate.passed ? "healthy" : "degraded"} /><span>{gate.name} · {gate.detail}</span></li>)}</ul><p>Break-glass approval: {support.break_glass_policy.approval_required ? "required" : "not reported"}; audited: {support.break_glass_policy.audited ? "yes" : "no"}.</p></section><section><h3>Runbooks & correlation</h3>{support.runbooks.length ? <ul className="compactList">{support.runbooks.map((runbook) => <li key={runbook.id}><b>{runbook.title}</b><span>{runbook.escalation_path}</span></li>)}</ul> : <p className="muted">No runbooks reported.</p>}<p>Request IDs: {support.recent_request_ids?.join(", ") || "Not reported"}</p></section><section><h3>Source states</h3>{Object.entries(sourceStates).map(([name, state]) => <p key={name}><b>{name}</b>: {state}</p>)}</section></div></details>;
}
