"use client";

import { Empty, StatusBadge } from "@/components/ui/primitives";
import type { ConsoleController } from "@/features/console/types";
import type { ObservabilityModel } from "@/features/observability/observability-view";
import { safeLogMessage } from "@/features/observability/data";
import { Fact, formatObserved } from "@/features/observability/shared";

export function IncidentsTab({ console, model }: { console: ConsoleController; model: ObservabilityModel }) {
  const selectedID = console.route.incident || "";
  const selected = model.data.selectedIncident;
  const evidence = model.data.evidence;
  return <div className="masterDetail incidentMaster"><section className="masterList"><div className="sectionHeading"><div><p className="eyebrow">Factual inventory</p><h2>Incidents</h2></div><span>{model.data.incidents.length}</span></div>{model.data.sources.incidents === "unavailable" ? <p className="truthCallout">Incident source unavailable. No empty count is inferred.</p> : null}{model.data.incidents.length ? <ul>{model.data.incidents.map((incident) => <li key={incident.incident_id}><button aria-pressed={selectedID === incident.incident_id} onClick={() => console.navigate({ incident: incident.incident_id })} type="button"><span><strong>{incident.incident_id}</strong><small>{incident.service_id || "Service not reported"} · {incident.node_id || "Node not reported"}</small><small>{formatObserved(incident.created_at_unix)}</small></span><StatusBadge value={incident.severity || incident.status} /></button></li>)}</ul> : <Empty text="No incident records were returned." />}</section><section className="detailPanel">{selected ? <IncidentDetail console={console} model={model} incident={selected} evidence={evidence} /> : <Empty title="Select an incident" text="Choose an inventory record to inspect evidence and next action." />}</section></div>;
}

function IncidentDetail({ console, model, incident, evidence }: { console: ConsoleController; model: ObservabilityModel; incident: NonNullable<ObservabilityModel["data"]["selectedIncident"]>; evidence: ObservabilityModel["data"]["evidence"] }) {
  const identity = `${incident.service_id ? ` --service-id ${incident.service_id}` : ""}${incident.node_id ? ` --node-id ${incident.node_id}` : ""}`;
  return <><div className="detailHeading"><div><p className="eyebrow">Incident detail</p><h2>{incident.incident_id}</h2><p>{incident.service_id || "Service not reported"} · {incident.node_id || "Node not reported"} · {incident.pod_id || "Pod not reported"}</p></div><StatusBadge value={incident.severity || incident.status} /></div><dl className="evidenceGrid"><Fact label="Status" value={incident.status} /><Fact label="Started" value={formatObserved(incident.created_at_unix)} /><Fact label="Anomaly" value={incident.anomaly_type || "Not reported"} /><Fact label="MTTR" value={incident.mttr_seconds === undefined ? "Not reported" : `${incident.mttr_seconds}s`} /></dl>{model.data.evidenceState === "loading" ? <Empty title="Loading evidence…" text="Reading bounded Agent evidence." /> : model.data.evidenceState === "unavailable" ? <p className="truthCallout"><b>Evidence unavailable</b><br />The UI fails closed and does not infer completeness. {model.data.evidenceError}</p> : evidence ? <EvidencePanel evidence={evidence} /> : <Empty text="No evidence returned." />}<section className="nextAction"><h3>Next action</h3><p>Investigation can continue with logs, deployment facts, or the runbook. Approval and execution continue in the CLI because private approval material belongs in the OS secure store.</p><div className="detailActions"><button onClick={() => console.navigate({ tab: "logs", service: incident.service_id || "" })} type="button">View logs</button><button onClick={() => console.navigate({ view: "delivery", tab: "deployments", service: incident.service_id || "" })} type="button">View deployments</button><span className="cliHandoff"><b>Continue in CLI</b><code>opsi action preflight --project-id {incident.project_id} --kind incident_resolve --incident-id {incident.incident_id}{identity}</code><code>opsi action approve &lt;challenge-id&gt; --project-id {incident.project_id} --device-id &lt;device-id&gt;</code><code>opsi action execute &lt;challenge-id&gt; --project-id {incident.project_id}</code></span></div></section></>;
}

function EvidencePanel({ evidence }: { evidence: NonNullable<ObservabilityModel["data"]["evidence"]> }) {
  const partial = evidence.coverage.some((item) => item.status !== "available" || item.truncated) || Boolean(evidence.truncations?.length);
  return <div className="evidenceStack"><div className="evidenceBanner"><StatusBadge value={partial ? "degraded" : "healthy"} /><span>{partial ? "Partial evidence" : "Evidence complete for reported sources"}</span><code>{evidence.content_sha256}</code></div><dl className="evidenceGrid"><Fact label="Window start" value={formatObserved(evidence.observation_window.start_unix)} /><Fact label="Window end" value={formatObserved(evidence.observation_window.end_unix)} /><Fact label="Desired digest" value={evidence.deployment.desired_digest || "Not reported"} /><Fact label="Observed digest" value={evidence.deployment.observed_digest || "Not reported"} /><Fact label="Rollout" value={evidence.rollout.state || "Not reported"} /><Fact label="Readiness hash" value={evidence.rollout.readiness_hash || "Not reported"} /></dl><section><h3>Source coverage</h3><ul className="compactList">{evidence.coverage.map((item) => <li key={item.source}><StatusBadge value={item.status} /><span>{item.source} · {item.item_count} items{item.truncated ? " · truncated" : ""}{item.reason_code ? ` · ${item.reason_code}` : ""}</span></li>)}</ul></section><section><h3>Timeline</h3>{evidence.timeline?.length ? <ol className="eventTimeline">{evidence.timeline.map((item, index) => <li key={`${item.observed_at_unix}-${index}`}><span aria-hidden="true" /><div><b>{item.kind}</b><p>{safeLogMessage(item.detail || "No detail reported")}</p><small>{item.source} · {formatObserved(item.observed_at_unix)}{item.untrusted_content ? " · untrusted text" : ""}</small></div></li>)}</ol> : <p className="muted">No timeline entries reported.</p>}</section><div className="observabilityColumns"><section><h3>Pods</h3>{evidence.pods?.length ? <ul className="compactList">{evidence.pods.map((pod) => <li key={pod.pod_id}><b>{pod.pod_id}</b><span>{pod.ready_containers}/{pod.total_containers} ready · {pod.restart_count} restarts · node {pod.node_id || "not reported"}</span></li>)}</ul> : <p className="muted">No pod facts reported.</p>}</section><section><h3>Log fingerprints</h3>{evidence.log_fingerprints?.length ? <ul className="compactList">{evidence.log_fingerprints.map((log) => <li key={log.fingerprint}><b>{log.fingerprint}</b><span>{log.count} · {safeLogMessage(log.excerpt || "No excerpt reported")}</span></li>)}</ul> : <p className="muted">No log groups reported.</p>}</section></div>{evidence.truncations?.length ? <p className="truthCallout">Truncated sections: {evidence.truncations.map((item) => `${item.section} (${item.omitted_items} omitted)`).join(", ")}</p> : null}<details><summary>Technical evidence metadata</summary><pre className="evidenceCode">{JSON.stringify({ schema_version: evidence.schema_version, rollout: evidence.rollout, audit_references: evidence.audit_references }, null, 2)}</pre></details></div>;
}
