"use client";

import { useEffect, useMemo } from "react";
import { Empty, StatusBadge } from "@/components/ui/primitives";
import type { ConsoleController } from "@/features/console/types";
import { safeLogMessage } from "@/features/observability/data";
import type { ObservabilityModel } from "@/features/observability/observability-view";
import { formatObserved } from "@/features/observability/shared";

export function LogsTab({ console, model }: { console: ConsoleController; model: ObservabilityModel }) {
  const service = console.route.service || "";
  const level = console.route.level || "";
  const query = console.route.query || "";
  useEffect(() => { void model.loadLogs({ serviceID: service || undefined }); }, [console.state.project?.id, service]); // eslint-disable-line react-hooks/exhaustive-deps
  const rows = useMemo(() => model.data.logs.rows.filter((row) => (!level || row.level === level) && (!query || `${row.service_id ?? ""} ${row.message}`.toLowerCase().includes(query.toLowerCase()))), [model.data.logs.rows, level, query]);
  const levels = [...new Set(model.data.logs.rows.map((row) => row.level))].sort();
  return <div className="observabilityStack"><div className="observabilityHero"><div><p className="eyebrow">Paginated explorer</p><h2>Logs</h2><p>Bounded, redacted Agent pages with explicit refresh and cursor pagination.</p></div><button disabled={model.data.logs.source === "loading"} onClick={() => void model.loadLogs({ serviceID: service || undefined })} type="button">Refresh logs</button></div><div className="logFilters"><label>Service<select className="select" name="service" onChange={(event) => console.navigate({ service: event.target.value, cursor: "" })} value={service}><option value="">All loaded services</option>{console.state.services.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Level<select className="select" name="level" onChange={(event) => console.navigate({ level: event.target.value })} value={level}><option value="">All levels on loaded page</option>{levels.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><label>Search loaded page<input autoComplete="off" className="field" name="query" onChange={(event) => console.navigate({ query: event.target.value })} placeholder="Search message text…" type="search" value={query} /></label></div><div className="logMeta"><span>Source: <b>{model.data.logs.source}</b></span><span>{rows.length} visible / {model.data.logs.rows.length} loaded</span><span>Messages are untrusted text</span></div>{model.data.logs.error ? <p className="inlineError" role="alert">{model.data.logs.error}. Last factual page is preserved.</p> : null}{rows.length ? <ol className="logList">{rows.map((row, index) => <li key={`${row.observed_unix}-${row.fingerprint}-${index}`}><time dateTime={new Date(row.observed_unix * 1000).toISOString()}>{formatObserved(row.observed_unix)}</time><StatusBadge value={row.level} /><strong>{row.service_id || "runtime"}</strong><p>{safeLogMessage(row.message)}</p><details><summary>Pod, namespace & fingerprint</summary><dl className="evidenceGrid"><div><dt>Pod</dt><dd>{row.pod_id || "Not reported"}</dd></div><div><dt>Namespace</dt><dd>{row.namespace || "Not reported"}</dd></div><div><dt>Fingerprint</dt><dd>{row.fingerprint || "Not reported"}</dd></div><div><dt>Trust</dt><dd>Untrusted content; rendered as text only</dd></div></dl></details></li>)}</ol> : model.data.logs.source !== "loading" ? <Empty text="No log rows match the loaded page and filters." /> : <Empty title="Loading logs…" text="Reading one bounded Agent page." />}{model.data.logs.nextCursor ? <button onClick={() => void model.loadLogs({ serviceID: service || undefined, cursor: model.data.logs.nextCursor })} type="button">Load next page</button> : null}</div>;
}
