package assistant

const codexOutputSchema = `{
  "type":"object",
  "additionalProperties":false,
  "properties":{
    "message":{"type":"string"},
    "configuration_proposals":{"type":"array","items":{
      "type":"object","additionalProperties":false,
      "properties":{
        "application_id":{"type":"string"},
        "application_name":{"type":"string"},
        "environment_id":{"type":"string"},
        "rationale":{"type":"string"},
        "expected_revision":{"type":"integer","minimum":0},
        "expected_state_hash":{"type":"string"},
        "analysis_inputs_hash":{"type":"string"},
        "draft_json":{"type":"string"}
      },
      "required":["application_id","application_name","environment_id","rationale","expected_revision","expected_state_hash","analysis_inputs_hash","draft_json"]
    }},
    "source_patch_proposals":{"type":"array","items":{
      "type":"object","additionalProperties":false,
      "properties":{
        "project_id":{"type":"string"},
        "environment_id":{"type":"string"},
        "application_id":{"type":"string"},
        "source_commit":{"type":"string"},
        "application_root":{"type":"string"},
        "proposal_hash":{"type":"string"},
        "validation_status":{"type":"string","enum":["VALID","VALID_WITH_WARNINGS"]},
        "proposal":{
          "type":"object",
          "additionalProperties":false,
          "properties":{
            "project_id":{"type":"string"},
            "environment_id":{"type":"string"},
            "application_id":{"type":"string"},
            "provenance":{
              "type":"object",
              "additionalProperties":false,
              "properties":{
                "build_record_id":{"type":"string"},
                "source_commit":{"type":"string"},
                "application_root":{"type":"string"}
              },
              "required":["build_record_id","source_commit","application_root"]
            },
            "rationale":{
              "type":"object",
              "additionalProperties":false,
              "properties":{
                "observed_source":{"type":"string"},
                "opsi_facts":{"type":"string"},
                "inference":{"type":"string"}
              },
              "required":["observed_source","opsi_facts","inference"]
            },
            "files":{
              "type":"array",
              "items":{
                "type":"object",
                "additionalProperties":false,
                "properties":{
                  "path":{"type":"string"},
                  "base_blob_sha":{"type":"string"},
                  "unified_diff":{"type":"string"}
                },
                "required":["path","base_blob_sha","unified_diff"]
              }
            },
            "evidence":{
              "type":"array",
              "items":{
                "type":"object",
                "additionalProperties":false,
                "properties":{
                  "type":{"type":"string"},
                  "file":{"type":"string"},
                  "line":{"type":"integer"},
                  "reason":{"type":"string"},
                  "symbol":{"type":"string"}
                },
                "required":["type","file","line","reason","symbol"]
              }
            },
            "impact":{
              "type":"object",
              "additionalProperties":false,
              "properties":{
                "alternative_configuration_only_solution":{"type":"boolean"},
                "depends_on_unapplied_dependency_proposal":{"type":"boolean"}
              },
              "required":["alternative_configuration_only_solution","depends_on_unapplied_dependency_proposal"]
            }
          },
          "required":["project_id","environment_id","application_id","provenance","rationale","files","evidence","impact"]
        }
      },
      "required":["project_id","environment_id","application_id","source_commit","application_root","proposal_hash","validation_status","proposal"]
    }}
  },
  "required":["message","configuration_proposals","source_patch_proposals"]
}`
